#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0xbba89470, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0xb4211da4, __VMLINUX_SYMBOL_STR(pnfs_unregister_layoutdriver) },
	{ 0x2b0301ca, __VMLINUX_SYMBOL_STR(nfs4_schedule_session_recovery) },
	{ 0x3370e0a3, __VMLINUX_SYMBOL_STR(pnfs_nfs_generic_sync) },
	{ 0x6ebd14ab, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0x65e75cb6, __VMLINUX_SYMBOL_STR(__list_del_entry) },
	{ 0x12da5bb2, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0xaf5bf6ef, __VMLINUX_SYMBOL_STR(nfs_debug) },
	{ 0x7e708ebe, __VMLINUX_SYMBOL_STR(nfs4_pnfs_ds_connect) },
	{ 0x177c6a22, __VMLINUX_SYMBOL_STR(pnfs_generic_clear_request_commit) },
	{ 0x2e5810c6, __VMLINUX_SYMBOL_STR(__aeabi_unwind_cpp_pr1) },
	{ 0xa0fbac79, __VMLINUX_SYMBOL_STR(wake_up_bit) },
	{ 0x134bb9b3, __VMLINUX_SYMBOL_STR(page_address) },
	{ 0x9a07f4bb, __VMLINUX_SYMBOL_STR(nfs_init_cinfo) },
	{ 0x19f462ab, __VMLINUX_SYMBOL_STR(kfree_call_rcu) },
	{ 0x7272c3c8, __VMLINUX_SYMBOL_STR(cpu_online_mask) },
	{ 0x54dde71a, __VMLINUX_SYMBOL_STR(nfs_initiate_commit) },
	{ 0x59e8186a, __VMLINUX_SYMBOL_STR(pnfs_error_mark_layout_for_return) },
	{ 0xd43bbb46, __VMLINUX_SYMBOL_STR(nfs4_pnfs_ds_put) },
	{ 0x9413698e, __VMLINUX_SYMBOL_STR(put_rpccred) },
	{ 0x2a3aa678, __VMLINUX_SYMBOL_STR(_test_and_clear_bit) },
	{ 0x54bef45, __VMLINUX_SYMBOL_STR(layoutstats_timer) },
	{ 0xc87c1f84, __VMLINUX_SYMBOL_STR(ktime_get) },
	{ 0x239de645, __VMLINUX_SYMBOL_STR(rpc_restart_call) },
	{ 0xb1ad28e0, __VMLINUX_SYMBOL_STR(__gnu_mcount_nc) },
	{ 0xbfd03632, __VMLINUX_SYMBOL_STR(init_user_ns) },
	{ 0x27b90854, __VMLINUX_SYMBOL_STR(nfs4_mark_deviceid_unavailable) },
	{ 0xb5c036e1, __VMLINUX_SYMBOL_STR(__tracepoint_nfs4_pnfs_commit_ds) },
	{ 0xfa814e5a, __VMLINUX_SYMBOL_STR(nfs4_decode_mp_ds_addr) },
	{ 0xfeb99d0b, __VMLINUX_SYMBOL_STR(nfs_initiate_pgio) },
	{ 0x90cd47d9, __VMLINUX_SYMBOL_STR(nfs4_set_rw_stateid) },
	{ 0x51c7f10f, __VMLINUX_SYMBOL_STR(pnfs_generic_commit_pagelist) },
	{ 0x442a091f, __VMLINUX_SYMBOL_STR(__alloc_pages_nodemask) },
	{ 0x13530881, __VMLINUX_SYMBOL_STR(pnfs_generic_recover_commit_reqs) },
	{ 0x343a1a8, __VMLINUX_SYMBOL_STR(__list_add) },
	{ 0x395e4b51, __VMLINUX_SYMBOL_STR(nfs41_setup_sequence) },
	{ 0x7aa0348b, __VMLINUX_SYMBOL_STR(nfs4_sequence_done) },
	{ 0xd815526c, __VMLINUX_SYMBOL_STR(xdr_reserve_space) },
	{ 0xdc01d8a3, __VMLINUX_SYMBOL_STR(pnfs_generic_pg_test) },
	{ 0x8cd20c75, __VMLINUX_SYMBOL_STR(nfs4_schedule_lease_recovery) },
	{ 0xa538abe3, __VMLINUX_SYMBOL_STR(pnfs_update_layout) },
	{ 0xe0e2656d, __VMLINUX_SYMBOL_STR(make_kgid) },
	{ 0xc08f7356, __VMLINUX_SYMBOL_STR(rpc_exit) },
	{ 0x66a1baf3, __VMLINUX_SYMBOL_STR(pnfs_generic_pg_cleanup) },
	{ 0x35779860, __VMLINUX_SYMBOL_STR(pnfs_generic_write_commit_done) },
	{ 0xc0cd27a0, __VMLINUX_SYMBOL_STR(rpc_delay) },
	{ 0xdd0a2ba2, __VMLINUX_SYMBOL_STR(strlcat) },
	{ 0x7f120a0d, __VMLINUX_SYMBOL_STR(pnfs_generic_layout_insert_lseg) },
	{ 0x461ac467, __VMLINUX_SYMBOL_STR(xdr_init_decode_pages) },
	{ 0xbac3cbf2, __VMLINUX_SYMBOL_STR(ns_to_timespec64) },
	{ 0x98b742c3, __VMLINUX_SYMBOL_STR(rpc_call_start) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0x71c90087, __VMLINUX_SYMBOL_STR(memcmp) },
	{ 0x9fa097a0, __VMLINUX_SYMBOL_STR(nfs40_setup_sequence) },
	{ 0x851ac704, __VMLINUX_SYMBOL_STR(pnfs_read_resend_pnfs) },
	{ 0xd6b355ab, __VMLINUX_SYMBOL_STR(nfs4_find_get_deviceid) },
	{ 0x4c6175c4, __VMLINUX_SYMBOL_STR(nfs4_find_or_create_ds_client) },
	{ 0x6b9129c1, __VMLINUX_SYMBOL_STR(rpc_max_payload) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0x4b288433, __VMLINUX_SYMBOL_STR(nfs_pageio_reset_write_mds) },
	{ 0x521445b, __VMLINUX_SYMBOL_STR(list_del) },
	{ 0x87e563f6, __VMLINUX_SYMBOL_STR(pnfs_layout_mark_request_commit) },
	{ 0x8be2df9c, __VMLINUX_SYMBOL_STR(pnfs_destroy_layout) },
	{ 0xc3bfd264, __VMLINUX_SYMBOL_STR(nfs4_pnfs_ds_add) },
	{ 0x7fd22125, __VMLINUX_SYMBOL_STR(pnfs_layoutcommit_inode) },
	{ 0xa5ffc3c0, __VMLINUX_SYMBOL_STR(pnfs_put_lseg) },
	{ 0x8458f70b, __VMLINUX_SYMBOL_STR(contig_page_data) },
	{ 0x7b4bf46f, __VMLINUX_SYMBOL_STR(nfs4_put_deviceid_node) },
	{ 0x63432f79, __VMLINUX_SYMBOL_STR(pnfs_report_layoutstat) },
	{ 0xed15fb41, __VMLINUX_SYMBOL_STR(nfs4_print_deviceid) },
	{ 0x43059400, __VMLINUX_SYMBOL_STR(pnfs_set_layoutcommit) },
	{ 0x90b70b0e, __VMLINUX_SYMBOL_STR(pnfs_generic_scan_commit_lists) },
	{ 0x69d3558d, __VMLINUX_SYMBOL_STR(pnfs_generic_rw_release) },
	{ 0x568e5a7b, __VMLINUX_SYMBOL_STR(__free_pages) },
	{ 0x3ccc897f, __VMLINUX_SYMBOL_STR(make_kuid) },
	{ 0x306b51d7, __VMLINUX_SYMBOL_STR(nfs4_schedule_stateid_recovery) },
	{ 0xdb7305a1, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0x72350130, __VMLINUX_SYMBOL_STR(___ratelimit) },
	{ 0xcea977f8, __VMLINUX_SYMBOL_STR(nfs4_test_deviceid_unavailable) },
	{ 0xa02df320, __VMLINUX_SYMBOL_STR(nfs_map_string_to_numeric) },
	{ 0xf999267e, __VMLINUX_SYMBOL_STR(pnfs_generic_commit_release) },
	{ 0x90de3f5e, __VMLINUX_SYMBOL_STR(rpc_sleep_on) },
	{ 0x3577c6c9, __VMLINUX_SYMBOL_STR(pnfs_generic_pg_readpages) },
	{ 0x6ba3cb43, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0x9c0bd51f, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0x65994f1, __VMLINUX_SYMBOL_STR(xdr_encode_opaque_fixed) },
	{ 0x19503a3f, __VMLINUX_SYMBOL_STR(pnfs_read_done_resend_to_mds) },
	{ 0xe5919cb1, __VMLINUX_SYMBOL_STR(xdr_encode_opaque) },
	{ 0x3746285e, __VMLINUX_SYMBOL_STR(rpc_restart_call_prepare) },
	{ 0xf2c2d059, __VMLINUX_SYMBOL_STR(rpc_wake_up_queued_task) },
	{ 0x5da76e99, __VMLINUX_SYMBOL_STR(pnfs_generic_pg_writepages) },
	{ 0xe92c510d, __VMLINUX_SYMBOL_STR(nfs_direct_set_resched_writes) },
	{ 0xa5e56701, __VMLINUX_SYMBOL_STR(pnfs_generic_prepare_to_resend_writes) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x9d669763, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0x729e8cc6, __VMLINUX_SYMBOL_STR(__tracepoint_nfs4_pnfs_read) },
	{ 0x421b2648, __VMLINUX_SYMBOL_STR(pnfs_write_done_resend_to_mds) },
	{ 0x3be97fa1, __VMLINUX_SYMBOL_STR(rpc_wake_up) },
	{ 0x8f678b07, __VMLINUX_SYMBOL_STR(__stack_chk_guard) },
	{ 0x676bbc0f, __VMLINUX_SYMBOL_STR(_set_bit) },
	{ 0xc7e578a5, __VMLINUX_SYMBOL_STR(rpc_count_iostats_metrics) },
	{ 0x680cbdc4, __VMLINUX_SYMBOL_STR(xdr_inline_decode) },
	{ 0x4d88dcb2, __VMLINUX_SYMBOL_STR(__tracepoint_nfs4_pnfs_write) },
	{ 0xb81960ca, __VMLINUX_SYMBOL_STR(snprintf) },
	{ 0xca54fee, __VMLINUX_SYMBOL_STR(_test_and_set_bit) },
	{ 0x350cb0c1, __VMLINUX_SYMBOL_STR(nfs_pageio_reset_read_mds) },
	{ 0xa8f070ee, __VMLINUX_SYMBOL_STR(nfs4_init_deviceid_node) },
	{ 0x49ebacbd, __VMLINUX_SYMBOL_STR(_clear_bit) },
	{ 0x72aedf9c, __VMLINUX_SYMBOL_STR(param_ops_uint) },
	{ 0x31572230, __VMLINUX_SYMBOL_STR(nfs_remove_bad_delegation) },
	{ 0x334b617c, __VMLINUX_SYMBOL_STR(xdr_set_scratch_buffer) },
	{ 0x8ae3155d, __VMLINUX_SYMBOL_STR(nfs_writeback_update_inode) },
	{ 0xccbd81f6, __VMLINUX_SYMBOL_STR(pnfs_register_layoutdriver) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=";

