#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0xbba89470, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x8e9a6a82, __VMLINUX_SYMBOL_STR(inet_csk_reqsk_queue_drop) },
	{ 0x59814a84, __VMLINUX_SYMBOL_STR(dccp_statistics) },
	{ 0x49045426, __VMLINUX_SYMBOL_STR(icmp_err_convert) },
	{ 0xc65f4a23, __VMLINUX_SYMBOL_STR(dccp_init_sock) },
	{ 0xbd07189f, __VMLINUX_SYMBOL_STR(__ip_route_output_key_hash) },
	{ 0xfc80bf83, __VMLINUX_SYMBOL_STR(dccp_set_state) },
	{ 0x84a83697, __VMLINUX_SYMBOL_STR(ip_getsockopt) },
	{ 0x2e5810c6, __VMLINUX_SYMBOL_STR(__aeabi_unwind_cpp_pr1) },
	{ 0x7af6ec86, __VMLINUX_SYMBOL_STR(inet_unhash) },
	{ 0xd16b11, __VMLINUX_SYMBOL_STR(inet_twsk_put) },
	{ 0xb0596156, __VMLINUX_SYMBOL_STR(dccp_hashinfo) },
	{ 0x6c5e92d1, __VMLINUX_SYMBOL_STR(ip_setsockopt) },
	{ 0x7972641b, __VMLINUX_SYMBOL_STR(dccp_sendmsg) },
	{ 0xb0e8babc, __VMLINUX_SYMBOL_STR(ip_build_and_send_pkt) },
	{ 0x6e0104d7, __VMLINUX_SYMBOL_STR(sk_setup_caps) },
	{ 0x9228cf4d, __VMLINUX_SYMBOL_STR(dccp_ctl_make_reset) },
	{ 0xe2971407, __VMLINUX_SYMBOL_STR(dccp_destroy_sock) },
	{ 0x39851b65, __VMLINUX_SYMBOL_STR(dccp_make_response) },
	{ 0xc8ed5ccd, __VMLINUX_SYMBOL_STR(sock_release) },
	{ 0x83caeed5, __VMLINUX_SYMBOL_STR(dst_release) },
	{ 0x14484340, __VMLINUX_SYMBOL_STR(dccp_send_sync) },
	{ 0x172738bc, __VMLINUX_SYMBOL_STR(dccp_rcv_established) },
	{ 0xb0b4d158, __VMLINUX_SYMBOL_STR(security_skb_classify_flow) },
	{ 0x34b92beb, __VMLINUX_SYMBOL_STR(inet_csk_prepare_forced_close) },
	{ 0xad9c80b1, __VMLINUX_SYMBOL_STR(dccp_create_openreq_child) },
	{ 0xb1ad28e0, __VMLINUX_SYMBOL_STR(__gnu_mcount_nc) },
	{ 0x2e4725b3, __VMLINUX_SYMBOL_STR(dccp_check_req) },
	{ 0x9dbb75dc, __VMLINUX_SYMBOL_STR(inet_sendmsg) },
	{ 0xb993b0f3, __VMLINUX_SYMBOL_STR(dccp_recvmsg) },
	{ 0x7c67d734, __VMLINUX_SYMBOL_STR(inet_del_protocol) },
	{ 0x6d59ea66, __VMLINUX_SYMBOL_STR(inet_sk_rebuild_header) },
	{ 0x7d11c268, __VMLINUX_SYMBOL_STR(jiffies) },
	{ 0xfa292346, __VMLINUX_SYMBOL_STR(dccp_ioctl) },
	{ 0x52405baf, __VMLINUX_SYMBOL_STR(dccp_setsockopt) },
	{ 0xb6f3a8cc, __VMLINUX_SYMBOL_STR(sock_common_recvmsg) },
	{ 0xc4ef99f8, __VMLINUX_SYMBOL_STR(sock_no_sendpage) },
	{ 0x7e078c01, __VMLINUX_SYMBOL_STR(dccp_child_process) },
	{ 0xe809ee90, __VMLINUX_SYMBOL_STR(__pskb_pull_tail) },
	{ 0x267cb8a7, __VMLINUX_SYMBOL_STR(sock_no_mmap) },
	{ 0x5f754e5a, __VMLINUX_SYMBOL_STR(memset) },
	{ 0x4c504b72, __VMLINUX_SYMBOL_STR(sock_no_socketpair) },
	{ 0xb428c2f6, __VMLINUX_SYMBOL_STR(skb_checksum) },
	{ 0x1885258d, __VMLINUX_SYMBOL_STR(unregister_pernet_subsys) },
	{ 0x710d755e, __VMLINUX_SYMBOL_STR(dccp_parse_options) },
	{ 0x21c92e4e, __VMLINUX_SYMBOL_STR(dccp_getsockopt) },
	{ 0xb2d85899, __VMLINUX_SYMBOL_STR(inet_csk_update_pmtu) },
	{ 0xc2a7502f, __VMLINUX_SYMBOL_STR(security_sk_classify_flow) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0xbec02345, __VMLINUX_SYMBOL_STR(inet_csk_route_req) },
	{ 0xacf923df, __VMLINUX_SYMBOL_STR(inet_csk_route_child_sock) },
	{ 0x7621ab43, __VMLINUX_SYMBOL_STR(kmem_cache_free) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0xff21673d, __VMLINUX_SYMBOL_STR(inet_hash_connect) },
	{ 0xe6ff079e, __VMLINUX_SYMBOL_STR(dccp_reqsk_init) },
	{ 0x6a13def7, __VMLINUX_SYMBOL_STR(dev_get_by_index_rcu) },
	{ 0x98db14d5, __VMLINUX_SYMBOL_STR(dccp_close) },
	{ 0xbf842eae, __VMLINUX_SYMBOL_STR(sk_free) },
	{ 0x6f9c94c6, __VMLINUX_SYMBOL_STR(inet_shutdown) },
	{ 0x68e447fb, __VMLINUX_SYMBOL_STR(inet_add_protocol) },
	{ 0x9a123b7, __VMLINUX_SYMBOL_STR(dccp_orphan_count) },
	{ 0x497018ad, __VMLINUX_SYMBOL_STR(dccp_sync_mss) },
	{ 0xe9687eb8, __VMLINUX_SYMBOL_STR(inet_accept) },
	{ 0xfdbbd386, __VMLINUX_SYMBOL_STR(inet_csk_reqsk_queue_drop_and_put) },
	{ 0x5118c382, __VMLINUX_SYMBOL_STR(secure_dccp_sequence_number) },
	{ 0x787cd477, __VMLINUX_SYMBOL_STR(inet_ioctl) },
	{ 0x3ce7dbd3, __VMLINUX_SYMBOL_STR(inet_csk_get_port) },
	{ 0x14b80968, __VMLINUX_SYMBOL_STR(dccp_death_row) },
	{ 0xc1a205f4, __VMLINUX_SYMBOL_STR(inet_ctl_sock_create) },
	{ 0x8698fc78, __VMLINUX_SYMBOL_STR(dccp_poll) },
	{ 0x475adf, __VMLINUX_SYMBOL_STR(inet_hash) },
	{ 0x71314b04, __VMLINUX_SYMBOL_STR(proto_register) },
	{ 0x5b59d33b, __VMLINUX_SYMBOL_STR(dccp_disconnect) },
	{ 0xb43b38e3, __VMLINUX_SYMBOL_STR(__sk_dst_check) },
	{ 0x1adc358d, __VMLINUX_SYMBOL_STR(inet_release) },
	{ 0x43c15b23, __VMLINUX_SYMBOL_STR(dccp_done) },
	{ 0xdb7305a1, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0x6b2a3112, __VMLINUX_SYMBOL_STR(inet_reqsk_alloc) },
	{ 0x844c5263, __VMLINUX_SYMBOL_STR(kfree_skb) },
	{ 0x552b0d28, __VMLINUX_SYMBOL_STR(proto_unregister) },
	{ 0x6b542ada, __VMLINUX_SYMBOL_STR(inet_stream_connect) },
	{ 0x3db5ea4f, __VMLINUX_SYMBOL_STR(inet_getname) },
	{ 0x39d32af0, __VMLINUX_SYMBOL_STR(inet_ehash_nolisten) },
	{ 0x5fd9b2f, __VMLINUX_SYMBOL_STR(register_pernet_subsys) },
	{ 0x85bc1e78, __VMLINUX_SYMBOL_STR(inet_csk_bind_conflict) },
	{ 0x4cdd391d, __VMLINUX_SYMBOL_STR(dccp_feat_list_purge) },
	{ 0x9c0bd51f, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0xd170a69b, __VMLINUX_SYMBOL_STR(sk_receive_skb) },
	{ 0x6b3db47a, __VMLINUX_SYMBOL_STR(inet_csk_reqsk_queue_hash_add) },
	{ 0x2a18c74, __VMLINUX_SYMBOL_STR(nf_conntrack_destroy) },
	{ 0x16cb9ead, __VMLINUX_SYMBOL_STR(ip_route_output_flow) },
	{ 0xf6ebc03b, __VMLINUX_SYMBOL_STR(net_ratelimit) },
	{ 0xa508c5e1, __VMLINUX_SYMBOL_STR(sock_common_setsockopt) },
	{ 0x6f3634f5, __VMLINUX_SYMBOL_STR(__xfrm_policy_check) },
	{ 0x8f53584d, __VMLINUX_SYMBOL_STR(inet_register_protosw) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0xe1761617, __VMLINUX_SYMBOL_STR(security_inet_conn_request) },
	{ 0x6bb9abde, __VMLINUX_SYMBOL_STR(inet_dccp_listen) },
	{ 0x865c2aec, __VMLINUX_SYMBOL_STR(__inet_inherit_port) },
	{ 0x16fdd531, __VMLINUX_SYMBOL_STR(inet_bind) },
	{ 0x3a6add0e, __VMLINUX_SYMBOL_STR(sock_common_getsockopt) },
	{ 0x86be7924, __VMLINUX_SYMBOL_STR(dccp_packet_name) },
	{ 0x1930775a, __VMLINUX_SYMBOL_STR(inet_csk_accept) },
	{ 0x8f678b07, __VMLINUX_SYMBOL_STR(__stack_chk_guard) },
	{ 0xe2323d0a, __VMLINUX_SYMBOL_STR(__inet_lookup_listener) },
	{ 0xd8ee5eaf, __VMLINUX_SYMBOL_STR(dccp_reqsk_send_ack) },
	{ 0xebb6a21a, __VMLINUX_SYMBOL_STR(dccp_rcv_state_process) },
	{ 0xba33dbbe, __VMLINUX_SYMBOL_STR(dccp_connect) },
	{ 0x3009ebcf, __VMLINUX_SYMBOL_STR(dccp_shutdown) },
	{ 0x57fd2efa, __VMLINUX_SYMBOL_STR(ip_queue_xmit) },
	{ 0x71fff12d, __VMLINUX_SYMBOL_STR(inet_unregister_protosw) },
	{ 0xea5413a6, __VMLINUX_SYMBOL_STR(inet_csk_addr2sockaddr) },
	{ 0x9118cc8f, __VMLINUX_SYMBOL_STR(__inet_lookup_established) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=dccp";

