#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0xbba89470, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0xbb53c6ea, __VMLINUX_SYMBOL_STR(kmem_cache_destroy) },
	{ 0x6ebd14ab, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0x1265335d, __VMLINUX_SYMBOL_STR(ata_std_prereset) },
	{ 0xc5a74ef0, __VMLINUX_SYMBOL_STR(ata_port_wait_eh) },
	{ 0x65e75cb6, __VMLINUX_SYMBOL_STR(__list_del_entry) },
	{ 0x12da5bb2, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0xf9a482f9, __VMLINUX_SYMBOL_STR(msleep) },
	{ 0x9331b6d5, __VMLINUX_SYMBOL_STR(scsi_change_queue_depth) },
	{ 0x62bf1cb8, __VMLINUX_SYMBOL_STR(sas_remove_children) },
	{ 0x76056570, __VMLINUX_SYMBOL_STR(sas_release_transport) },
	{ 0x2e5810c6, __VMLINUX_SYMBOL_STR(__aeabi_unwind_cpp_pr1) },
	{ 0x6c09c2a4, __VMLINUX_SYMBOL_STR(del_timer) },
	{ 0x134bb9b3, __VMLINUX_SYMBOL_STR(page_address) },
	{ 0x1e5e04bc, __VMLINUX_SYMBOL_STR(blk_abort_request) },
	{ 0xcc9905c, __VMLINUX_SYMBOL_STR(scsi_block_requests) },
	{ 0x9dbbd5e1, __VMLINUX_SYMBOL_STR(ata_std_sched_eh) },
	{ 0xc8b57c27, __VMLINUX_SYMBOL_STR(autoremove_wake_function) },
	{ 0x251c3a0, __VMLINUX_SYMBOL_STR(sas_port_free) },
	{ 0x46f6669, __VMLINUX_SYMBOL_STR(dev_printk) },
	{ 0xfaf72c25, __VMLINUX_SYMBOL_STR(sas_phy_add) },
	{ 0x2af17440, __VMLINUX_SYMBOL_STR(scsi_unblock_requests) },
	{ 0x23528cb8, __VMLINUX_SYMBOL_STR(ata_sas_slave_configure) },
	{ 0xf9aed1db, __VMLINUX_SYMBOL_STR(ata_scsi_cmd_error_handler) },
	{ 0x7f782742, __VMLINUX_SYMBOL_STR(sas_port_add_phy) },
	{ 0x2a3aa678, __VMLINUX_SYMBOL_STR(_test_and_clear_bit) },
	{ 0xd5152710, __VMLINUX_SYMBOL_STR(sg_next) },
	{ 0xb1ad28e0, __VMLINUX_SYMBOL_STR(__gnu_mcount_nc) },
	{ 0x1504b768, __VMLINUX_SYMBOL_STR(sas_rphy_free) },
	{ 0x9580deb, __VMLINUX_SYMBOL_STR(init_timer_key) },
	{ 0xf5d58d2, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0xd6ff25ac, __VMLINUX_SYMBOL_STR(sas_port_delete_phy) },
	{ 0xd6152976, __VMLINUX_SYMBOL_STR(sas_rphy_add) },
	{ 0xa18f9ea7, __VMLINUX_SYMBOL_STR(ata_sas_port_suspend) },
	{ 0x767f4ffc, __VMLINUX_SYMBOL_STR(ata_sas_port_init) },
	{ 0x7d11c268, __VMLINUX_SYMBOL_STR(jiffies) },
	{ 0x343a1a8, __VMLINUX_SYMBOL_STR(__list_add) },
	{ 0x5e267715, __VMLINUX_SYMBOL_STR(sas_port_delete) },
	{ 0x21818d12, __VMLINUX_SYMBOL_STR(ata_sas_async_probe) },
	{ 0x275ef902, __VMLINUX_SYMBOL_STR(__init_waitqueue_head) },
	{ 0x419535e2, __VMLINUX_SYMBOL_STR(sas_attach_transport) },
	{ 0x76ac3c06, __VMLINUX_SYMBOL_STR(wait_for_completion) },
	{ 0xb1b4b3c6, __VMLINUX_SYMBOL_STR(kmap_atomic) },
	{ 0x2939d29a, __VMLINUX_SYMBOL_STR(scsi_is_host_device) },
	{ 0xb3f75325, __VMLINUX_SYMBOL_STR(sas_rphy_delete) },
	{ 0xfa2a45e, __VMLINUX_SYMBOL_STR(__memzero) },
	{ 0x9a7422f3, __VMLINUX_SYMBOL_STR(ata_sas_port_stop) },
	{ 0x3987f01, __VMLINUX_SYMBOL_STR(scsi_queue_work) },
	{ 0xd0b5efeb, __VMLINUX_SYMBOL_STR(sas_expander_alloc) },
	{ 0x11089ac7, __VMLINUX_SYMBOL_STR(_ctype) },
	{ 0x51d559d1, __VMLINUX_SYMBOL_STR(_raw_spin_unlock_irqrestore) },
	{ 0x61f320d5, __VMLINUX_SYMBOL_STR(sas_read_port_mode_page) },
	{ 0x23fd6c4e, __VMLINUX_SYMBOL_STR(mutex_lock_interruptible) },
	{ 0xe870d825, __VMLINUX_SYMBOL_STR(sas_end_device_alloc) },
	{ 0x7ac5b069, __VMLINUX_SYMBOL_STR(__mutex_init) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0x71c90087, __VMLINUX_SYMBOL_STR(memcmp) },
	{ 0xb02cc771, __VMLINUX_SYMBOL_STR(ata_std_error_handler) },
	{ 0x4cb440ce, __VMLINUX_SYMBOL_STR(ata_scsi_port_error_handler) },
	{ 0xa8ce49f0, __VMLINUX_SYMBOL_STR(ata_sas_port_start) },
	{ 0xa1c76e0a, __VMLINUX_SYMBOL_STR(_cond_resched) },
	{ 0x6944cf9a, __VMLINUX_SYMBOL_STR(ata_std_qc_defer) },
	{ 0x7621ab43, __VMLINUX_SYMBOL_STR(kmem_cache_free) },
	{ 0xdab6f3a5, __VMLINUX_SYMBOL_STR(sas_port_mark_backlink) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0xaf835ade, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0xed93f29e, __VMLINUX_SYMBOL_STR(__kunmap_atomic) },
	{ 0xb343f2b7, __VMLINUX_SYMBOL_STR(sas_port_add) },
	{ 0x521445b, __VMLINUX_SYMBOL_STR(list_del) },
	{ 0x1bb31047, __VMLINUX_SYMBOL_STR(add_timer) },
	{ 0xf811e69d, __VMLINUX_SYMBOL_STR(scsi_eh_flush_done_q) },
	{ 0xbf9eea5f, __VMLINUX_SYMBOL_STR(ata_port_schedule_eh) },
	{ 0xb1c0c1c2, __VMLINUX_SYMBOL_STR(async_schedule_domain) },
	{ 0x4827e69a, __VMLINUX_SYMBOL_STR(ata_sas_port_alloc) },
	{ 0x44604728, __VMLINUX_SYMBOL_STR(ata_noop_qc_prep) },
	{ 0xcc2bf4bf, __VMLINUX_SYMBOL_STR(scsi_eh_finish_cmd) },
	{ 0xa0c4b361, __VMLINUX_SYMBOL_STR(sas_phy_free) },
	{ 0xf8625e4e, __VMLINUX_SYMBOL_STR(_dev_info) },
	{ 0x3621cbb8, __VMLINUX_SYMBOL_STR(kmem_cache_alloc) },
	{ 0x73c832f2, __VMLINUX_SYMBOL_STR(ata_dev_classify) },
	{ 0xc907fa9a, __VMLINUX_SYMBOL_STR(put_device) },
	{ 0xdb7305a1, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0x6cd21997, __VMLINUX_SYMBOL_STR(ata_tf_to_fis) },
	{ 0xd62c833f, __VMLINUX_SYMBOL_STR(schedule_timeout) },
	{ 0x1000e51, __VMLINUX_SYMBOL_STR(schedule) },
	{ 0x3507a132, __VMLINUX_SYMBOL_STR(_raw_spin_lock_irq) },
	{ 0xa956a33d, __VMLINUX_SYMBOL_STR(sas_phy_alloc) },
	{ 0xfba796b9, __VMLINUX_SYMBOL_STR(ata_wait_after_reset) },
	{ 0x6ba3cb43, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0x9c0bd51f, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0x485ec4d6, __VMLINUX_SYMBOL_STR(__dynamic_dev_dbg) },
	{ 0x598542b2, __VMLINUX_SYMBOL_STR(_raw_spin_lock_irqsave) },
	{ 0xd2508b7d, __VMLINUX_SYMBOL_STR(get_device) },
	{ 0x2a5a9212, __VMLINUX_SYMBOL_STR(kmem_cache_create) },
	{ 0x26c90ea4, __VMLINUX_SYMBOL_STR(scsi_eh_get_sense) },
	{ 0xd85cd67e, __VMLINUX_SYMBOL_STR(__wake_up) },
	{ 0x344b7739, __VMLINUX_SYMBOL_STR(prepare_to_wait_event) },
	{ 0x822137e2, __VMLINUX_SYMBOL_STR(arm_heavy_mb) },
	{ 0x1e047854, __VMLINUX_SYMBOL_STR(warn_slowpath_fmt) },
	{ 0x82701365, __VMLINUX_SYMBOL_STR(int_to_scsilun) },
	{ 0xefdd2345, __VMLINUX_SYMBOL_STR(sg_init_one) },
	{ 0xb89e9de8, __VMLINUX_SYMBOL_STR(ata_sas_port_resume) },
	{ 0xa4f6893a, __VMLINUX_SYMBOL_STR(sas_port_get_phy) },
	{ 0x9c55cec, __VMLINUX_SYMBOL_STR(schedule_timeout_interruptible) },
	{ 0xbfbb46c2, __VMLINUX_SYMBOL_STR(scsi_eh_ready_devs) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x6ca4bf88, __VMLINUX_SYMBOL_STR(async_synchronize_full_domain) },
	{ 0x9d669763, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0x9304b6, __VMLINUX_SYMBOL_STR(ata_tf_from_fis) },
	{ 0x499cb58c, __VMLINUX_SYMBOL_STR(prepare_to_wait) },
	{ 0xf9a9e7a5, __VMLINUX_SYMBOL_STR(sas_port_alloc) },
	{ 0x999c5881, __VMLINUX_SYMBOL_STR(ata_host_init) },
	{ 0xaa956ee1, __VMLINUX_SYMBOL_STR(flush_kernel_dcache_page) },
	{ 0x90a46b77, __VMLINUX_SYMBOL_STR(request_firmware) },
	{ 0xa8c3bbc7, __VMLINUX_SYMBOL_STR(scsi_schedule_eh) },
	{ 0x1cfb04fa, __VMLINUX_SYMBOL_STR(finish_wait) },
	{ 0x40c01c2f, __VMLINUX_SYMBOL_STR(__init_swait_queue_head) },
	{ 0xb9367be5, __VMLINUX_SYMBOL_STR(dev_warn) },
	{ 0xc06ef735, __VMLINUX_SYMBOL_STR(ata_std_postreset) },
	{ 0x8f678b07, __VMLINUX_SYMBOL_STR(__stack_chk_guard) },
	{ 0x676bbc0f, __VMLINUX_SYMBOL_STR(_set_bit) },
	{ 0xec80a890, __VMLINUX_SYMBOL_STR(sas_rphy_unlink) },
	{ 0xc66e75bb, __VMLINUX_SYMBOL_STR(complete) },
	{ 0xca54fee, __VMLINUX_SYMBOL_STR(_test_and_set_bit) },
	{ 0xbe0c38ac, __VMLINUX_SYMBOL_STR(ata_sas_queuecmd) },
	{ 0x2c9723a9, __VMLINUX_SYMBOL_STR(ata_sas_port_destroy) },
	{ 0xa38602cd, __VMLINUX_SYMBOL_STR(drain_workqueue) },
	{ 0x49ebacbd, __VMLINUX_SYMBOL_STR(_clear_bit) },
	{ 0x566ee37b, __VMLINUX_SYMBOL_STR(sas_rphy_remove) },
	{ 0x3642a302, __VMLINUX_SYMBOL_STR(release_firmware) },
	{ 0xe8b4be75, __VMLINUX_SYMBOL_STR(ata_sas_scsi_ioctl) },
	{ 0x70ba7ca5, __VMLINUX_SYMBOL_STR(__ata_change_queue_depth) },
	{ 0x741575d1, __VMLINUX_SYMBOL_STR(ata_qc_complete) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=scsi_transport_sas";

