#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0xbba89470, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x6dc39bc, __VMLINUX_SYMBOL_STR(param_ops_bool) },
	{ 0x305b7db8, __VMLINUX_SYMBOL_STR(blk_mq_map_queue) },
	{ 0x58f930da, __VMLINUX_SYMBOL_STR(bus_unregister) },
	{ 0x8375d79d, __VMLINUX_SYMBOL_STR(ida_destroy) },
	{ 0x8c03d20c, __VMLINUX_SYMBOL_STR(destroy_workqueue) },
	{ 0xebfdb35, __VMLINUX_SYMBOL_STR(device_unregister) },
	{ 0xb0aaff4f, __VMLINUX_SYMBOL_STR(bus_register) },
	{ 0x5210a6d6, __VMLINUX_SYMBOL_STR(device_register) },
	{ 0x43a53735, __VMLINUX_SYMBOL_STR(__alloc_workqueue_key) },
	{ 0x2a5a9212, __VMLINUX_SYMBOL_STR(kmem_cache_create) },
	{ 0x466b85b8, __VMLINUX_SYMBOL_STR(libceph_compatible) },
	{ 0x6b2e3bcd, __VMLINUX_SYMBOL_STR(ceph_get_snap_context) },
	{ 0xd066f431, __VMLINUX_SYMBOL_STR(blk_mq_start_request) },
	{ 0x10e78fd, __VMLINUX_SYMBOL_STR(blk_mq_end_request) },
	{ 0x1c2da646, __VMLINUX_SYMBOL_STR(osd_req_op_raw_data_in_pages) },
	{ 0x2495f054, __VMLINUX_SYMBOL_STR(bio_advance) },
	{ 0xc0ea648a, __VMLINUX_SYMBOL_STR(bio_clone_bioset) },
	{ 0xeefb9277, __VMLINUX_SYMBOL_STR(fs_bio_set) },
	{ 0x71a50dbc, __VMLINUX_SYMBOL_STR(register_blkdev) },
	{ 0xdf46a547, __VMLINUX_SYMBOL_STR(add_disk) },
	{ 0x9bf5ef24, __VMLINUX_SYMBOL_STR(device_add) },
	{ 0x28352af3, __VMLINUX_SYMBOL_STR(dev_set_name) },
	{ 0x73a005d9, __VMLINUX_SYMBOL_STR(blk_queue_max_discard_sectors) },
	{ 0x96e2b7c2, __VMLINUX_SYMBOL_STR(blk_queue_io_opt) },
	{ 0x5a2302b1, __VMLINUX_SYMBOL_STR(blk_queue_io_min) },
	{ 0xbd56b78c, __VMLINUX_SYMBOL_STR(blk_queue_max_segment_size) },
	{ 0xea7c2202, __VMLINUX_SYMBOL_STR(blk_queue_max_segments) },
	{ 0x782973e1, __VMLINUX_SYMBOL_STR(blk_queue_max_hw_sectors) },
	{ 0x2320640c, __VMLINUX_SYMBOL_STR(blk_mq_init_queue) },
	{ 0x30461f7d, __VMLINUX_SYMBOL_STR(blk_mq_alloc_tag_set) },
	{ 0xb81960ca, __VMLINUX_SYMBOL_STR(snprintf) },
	{ 0xd90aec36, __VMLINUX_SYMBOL_STR(alloc_disk) },
	{ 0xcbee6439, __VMLINUX_SYMBOL_STR(ida_simple_get) },
	{ 0x343a1a8, __VMLINUX_SYMBOL_STR(__list_add) },
	{ 0xf209cb8d, __VMLINUX_SYMBOL_STR(ceph_open_session) },
	{ 0xb9a87b6, __VMLINUX_SYMBOL_STR(ceph_create_client) },
	{ 0xd4ee22ba, __VMLINUX_SYMBOL_STR(ceph_monc_wait_osdmap) },
	{ 0xa803d46d, __VMLINUX_SYMBOL_STR(ceph_monc_request_next_osdmap) },
	{ 0x7f50dbd5, __VMLINUX_SYMBOL_STR(ceph_monc_do_get_version) },
	{ 0xf35a2d59, __VMLINUX_SYMBOL_STR(ceph_pg_poolid_by_name) },
	{ 0xf5d58d2, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0xc7672334, __VMLINUX_SYMBOL_STR(ceph_destroy_options) },
	{ 0xa3fc7b77, __VMLINUX_SYMBOL_STR(ceph_compare_options) },
	{ 0xaf835ade, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0x40e9fb59, __VMLINUX_SYMBOL_STR(ceph_parse_options) },
	{ 0xe2fae716, __VMLINUX_SYMBOL_STR(kmemdup) },
	{ 0x6c1ce5ce, __VMLINUX_SYMBOL_STR(strcspn) },
	{ 0xc7ec6c27, __VMLINUX_SYMBOL_STR(strspn) },
	{ 0x97f26326, __VMLINUX_SYMBOL_STR(try_module_get) },
	{ 0x742bd36b, __VMLINUX_SYMBOL_STR(ceph_pg_pool_name_by_id) },
	{ 0xe2d5255a, __VMLINUX_SYMBOL_STR(strcmp) },
	{ 0xe2cba5da, __VMLINUX_SYMBOL_STR(ceph_osdc_create_event) },
	{ 0xe68dc15d, __VMLINUX_SYMBOL_STR(revalidate_disk) },
	{ 0x36ad0865, __VMLINUX_SYMBOL_STR(up_write) },
	{ 0x8f538c1b, __VMLINUX_SYMBOL_STR(down_write) },
	{ 0xd9ce8f0c, __VMLINUX_SYMBOL_STR(strnlen) },
	{ 0xae3515ba, __VMLINUX_SYMBOL_STR(ceph_create_snap_context) },
	{ 0x71c90087, __VMLINUX_SYMBOL_STR(memcmp) },
	{ 0xc499ae1e, __VMLINUX_SYMBOL_STR(kstrdup) },
	{ 0xa17ab2f5, __VMLINUX_SYMBOL_STR(ceph_copy_from_page_vector) },
	{ 0x7f0cd7b1, __VMLINUX_SYMBOL_STR(osd_req_op_cls_response_data_pages) },
	{ 0x3af47cea, __VMLINUX_SYMBOL_STR(osd_req_op_cls_request_data_pagelist) },
	{ 0xd813625e, __VMLINUX_SYMBOL_STR(ceph_pagelist_append) },
	{ 0x35db6c95, __VMLINUX_SYMBOL_STR(ceph_alloc_page_vector) },
	{ 0xb5a459dc, __VMLINUX_SYMBOL_STR(unregister_blkdev) },
	{ 0x898d455e, __VMLINUX_SYMBOL_STR(device_del) },
	{ 0x1bde3456, __VMLINUX_SYMBOL_STR(ceph_osdc_flush_notifies) },
	{ 0x996bdb64, __VMLINUX_SYMBOL_STR(_kstrtoul) },
	{ 0xc907fa9a, __VMLINUX_SYMBOL_STR(put_device) },
	{ 0x8800e33a, __VMLINUX_SYMBOL_STR(osd_req_op_cls_request_data_pages) },
	{ 0xcd5302e3, __VMLINUX_SYMBOL_STR(osd_req_op_cls_init) },
	{ 0xfa3fcbb8, __VMLINUX_SYMBOL_STR(__blk_mq_end_request) },
	{ 0x8d3c2bca, __VMLINUX_SYMBOL_STR(blk_update_request) },
	{ 0x49ebacbd, __VMLINUX_SYMBOL_STR(_clear_bit) },
	{ 0x3f688151, __VMLINUX_SYMBOL_STR(ceph_put_snap_context) },
	{ 0x29e1b020, __VMLINUX_SYMBOL_STR(ida_simple_remove) },
	{ 0x65e75cb6, __VMLINUX_SYMBOL_STR(__list_del_entry) },
	{ 0x9216ab14, __VMLINUX_SYMBOL_STR(ceph_osdc_cancel_event) },
	{ 0xdc4fb28b, __VMLINUX_SYMBOL_STR(ceph_osdc_set_request_linger) },
	{ 0xa999eca8, __VMLINUX_SYMBOL_STR(osd_req_op_watch_init) },
	{ 0xa087599b, __VMLINUX_SYMBOL_STR(osd_req_op_extent_osd_data_pages) },
	{ 0xe9529df4, __VMLINUX_SYMBOL_STR(osd_req_op_extent_osd_data_bio) },
	{ 0x45b21c19, __VMLINUX_SYMBOL_STR(osd_req_op_init) },
	{ 0xfc4dac00, __VMLINUX_SYMBOL_STR(osd_req_op_alloc_hint_init) },
	{ 0x7288f9bd, __VMLINUX_SYMBOL_STR(osd_req_op_extent_init) },
	{ 0x7a2add7d, __VMLINUX_SYMBOL_STR(current_kernel_time64) },
	{ 0x2d637789, __VMLINUX_SYMBOL_STR(ceph_osdc_build_request) },
	{ 0xb4ccb20c, __VMLINUX_SYMBOL_STR(bio_put) },
	{ 0x7621ab43, __VMLINUX_SYMBOL_STR(kmem_cache_free) },
	{ 0x92e31a77, __VMLINUX_SYMBOL_STR(ceph_release_page_vector) },
	{ 0xe302a04d, __VMLINUX_SYMBOL_STR(ceph_osdc_put_request) },
	{ 0xca54fee, __VMLINUX_SYMBOL_STR(_test_and_set_bit) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0xd2508b7d, __VMLINUX_SYMBOL_STR(get_device) },
	{ 0xb2d48a2e, __VMLINUX_SYMBOL_STR(queue_work_on) },
	{ 0xf0152426, __VMLINUX_SYMBOL_STR(set_disk_ro) },
	{ 0x3507a132, __VMLINUX_SYMBOL_STR(_raw_spin_lock_irq) },
	{ 0x353e3fa5, __VMLINUX_SYMBOL_STR(__get_user_4) },
	{ 0x5b24fba2, __VMLINUX_SYMBOL_STR(ceph_client_id) },
	{ 0x91715312, __VMLINUX_SYMBOL_STR(sprintf) },
	{ 0xab694444, __VMLINUX_SYMBOL_STR(bsearch) },
	{ 0x3454a49f, __VMLINUX_SYMBOL_STR(__module_get) },
	{ 0x182112f8, __VMLINUX_SYMBOL_STR(device_initialize) },
	{ 0x753e09ce, __VMLINUX_SYMBOL_STR(__init_rwsem) },
	{ 0x691274c3, __VMLINUX_SYMBOL_STR(module_put) },
	{ 0x7b843302, __VMLINUX_SYMBOL_STR(ceph_destroy_client) },
	{ 0x521445b, __VMLINUX_SYMBOL_STR(list_del) },
	{ 0x9c0bd51f, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0x4e3567f7, __VMLINUX_SYMBOL_STR(match_int) },
	{ 0x44e9a829, __VMLINUX_SYMBOL_STR(match_token) },
	{ 0xccff8621, __VMLINUX_SYMBOL_STR(blk_mq_free_tag_set) },
	{ 0xc4c08d84, __VMLINUX_SYMBOL_STR(blk_cleanup_queue) },
	{ 0xa193ad04, __VMLINUX_SYMBOL_STR(del_gendisk) },
	{ 0x7780f5a2, __VMLINUX_SYMBOL_STR(put_disk) },
	{ 0x1c1db89e, __VMLINUX_SYMBOL_STR(wait_for_completion_interruptible_timeout) },
	{ 0x8ebbcbce, __VMLINUX_SYMBOL_STR(ceph_osdc_start_request) },
	{ 0xf2c52689, __VMLINUX_SYMBOL_STR(complete_all) },
	{ 0x1e047854, __VMLINUX_SYMBOL_STR(warn_slowpath_fmt) },
	{ 0x194eb701, __VMLINUX_SYMBOL_STR(ceph_osdc_alloc_request) },
	{ 0xfa2a45e, __VMLINUX_SYMBOL_STR(__memzero) },
	{ 0xb1b4b3c6, __VMLINUX_SYMBOL_STR(kmap_atomic) },
	{ 0xed93f29e, __VMLINUX_SYMBOL_STR(__kunmap_atomic) },
	{ 0x47fd624e, __VMLINUX_SYMBOL_STR(flush_dcache_page) },
	{ 0x676bbc0f, __VMLINUX_SYMBOL_STR(_set_bit) },
	{ 0x6a112424, __VMLINUX_SYMBOL_STR(up_read) },
	{ 0xf2415352, __VMLINUX_SYMBOL_STR(down_read) },
	{ 0x40c01c2f, __VMLINUX_SYMBOL_STR(__init_swait_queue_head) },
	{ 0x9d669763, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0x3621cbb8, __VMLINUX_SYMBOL_STR(kmem_cache_alloc) },
	{ 0x12da5bb2, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0x97255bdf, __VMLINUX_SYMBOL_STR(strlen) },
	{ 0x6ba3cb43, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0x6ebd14ab, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x44b1d426, __VMLINUX_SYMBOL_STR(__dynamic_pr_debug) },
	{ 0x5905d3ea, __VMLINUX_SYMBOL_STR(ceph_osdc_cancel_request) },
	{ 0xbb53c6ea, __VMLINUX_SYMBOL_STR(kmem_cache_destroy) },
	{ 0xdb7305a1, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0x8f678b07, __VMLINUX_SYMBOL_STR(__stack_chk_guard) },
	{ 0x2e5810c6, __VMLINUX_SYMBOL_STR(__aeabi_unwind_cpp_pr1) },
	{ 0xb1ad28e0, __VMLINUX_SYMBOL_STR(__gnu_mcount_nc) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=libceph";

