#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0xbba89470, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x3349efff, __VMLINUX_SYMBOL_STR(drm_release) },
	{ 0x6d9ca629, __VMLINUX_SYMBOL_STR(drm_prime_gem_destroy) },
	{ 0xc60d0b67, __VMLINUX_SYMBOL_STR(drm_fb_helper_set_par) },
	{ 0x6ebd14ab, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0x65e75cb6, __VMLINUX_SYMBOL_STR(__list_del_entry) },
	{ 0x12da5bb2, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0x8ef918e9, __VMLINUX_SYMBOL_STR(drm_crtc_helper_set_config) },
	{ 0x725a8ddd, __VMLINUX_SYMBOL_STR(drm_dev_register) },
	{ 0x575a0ca3, __VMLINUX_SYMBOL_STR(drm_connector_unplug_all) },
	{ 0x115442ca, __VMLINUX_SYMBOL_STR(drm_gem_put_pages) },
	{ 0x90f50c13, __VMLINUX_SYMBOL_STR(drm_dev_alloc) },
	{ 0xf52b54c8, __VMLINUX_SYMBOL_STR(drm_fb_helper_initial_config) },
	{ 0x7aa1756e, __VMLINUX_SYMBOL_STR(kvfree) },
	{ 0x6579f854, __VMLINUX_SYMBOL_STR(param_ops_int) },
	{ 0x2e5810c6, __VMLINUX_SYMBOL_STR(__aeabi_unwind_cpp_pr1) },
	{ 0x134bb9b3, __VMLINUX_SYMBOL_STR(page_address) },
	{ 0x9cd92dd7, __VMLINUX_SYMBOL_STR(drm_gem_dmabuf_release) },
	{ 0xe5c4bb71, __VMLINUX_SYMBOL_STR(drm_mode_config_cleanup) },
	{ 0xa3ebe4e8, __VMLINUX_SYMBOL_STR(drm_unplug_dev) },
	{ 0x39a0686a, __VMLINUX_SYMBOL_STR(arm_dma_ops) },
	{ 0x4f43426d, __VMLINUX_SYMBOL_STR(drm_fb_helper_unlink_fbi) },
	{ 0x29bd9626, __VMLINUX_SYMBOL_STR(dma_buf_detach) },
	{ 0x1e9058c5, __VMLINUX_SYMBOL_STR(drm_fb_helper_debug_leave) },
	{ 0x6b06fdce, __VMLINUX_SYMBOL_STR(delayed_work_timer_fn) },
	{ 0x1afae5e7, __VMLINUX_SYMBOL_STR(down_interruptible) },
	{ 0x999d2771, __VMLINUX_SYMBOL_STR(drm_helper_probe_single_connector_modes) },
	{ 0xd5152710, __VMLINUX_SYMBOL_STR(sg_next) },
	{ 0xfb874611, __VMLINUX_SYMBOL_STR(drm_gem_free_mmap_offset) },
	{ 0xee846c58, __VMLINUX_SYMBOL_STR(drm_vblank_cleanup) },
	{ 0xb1ad28e0, __VMLINUX_SYMBOL_STR(__gnu_mcount_nc) },
	{ 0x9580deb, __VMLINUX_SYMBOL_STR(init_timer_key) },
	{ 0xf5d58d2, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0x5ffac64f, __VMLINUX_SYMBOL_STR(drm_dev_unref) },
	{ 0x28b4030e, __VMLINUX_SYMBOL_STR(drm_vblank_init) },
	{ 0xc0f66d34, __VMLINUX_SYMBOL_STR(drm_encoder_init) },
	{ 0xf76b0a59, __VMLINUX_SYMBOL_STR(read_current_timer) },
	{ 0x343a1a8, __VMLINUX_SYMBOL_STR(__list_add) },
	{ 0xae8eae1f, __VMLINUX_SYMBOL_STR(drm_connector_cleanup) },
	{ 0xb99ab20a, __VMLINUX_SYMBOL_STR(drm_fb_helper_unregister_fbi) },
	{ 0x97bedac7, __VMLINUX_SYMBOL_STR(dma_buf_vunmap) },
	{ 0xc3c00dc, __VMLINUX_SYMBOL_STR(usb_get_descriptor) },
	{ 0x16600b02, __VMLINUX_SYMBOL_STR(drm_fb_helper_pan_display) },
	{ 0xe707d823, __VMLINUX_SYMBOL_STR(__aeabi_uidiv) },
	{ 0xb637065d, __VMLINUX_SYMBOL_STR(drm_helper_connector_dpms) },
	{ 0x5f754e5a, __VMLINUX_SYMBOL_STR(memset) },
	{ 0xa776c9f6, __VMLINUX_SYMBOL_STR(drm_mode_connector_attach_encoder) },
	{ 0x3744cf36, __VMLINUX_SYMBOL_STR(vmalloc_to_pfn) },
	{ 0x51d559d1, __VMLINUX_SYMBOL_STR(_raw_spin_unlock_irqrestore) },
	{ 0xf53daa4b, __VMLINUX_SYMBOL_STR(drm_prime_pages_to_sg) },
	{ 0x3683ad6f, __VMLINUX_SYMBOL_STR(usb_deregister) },
	{ 0xeda005dd, __VMLINUX_SYMBOL_STR(drm_helper_mode_fill_fb_struct) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0x203dfdfa, __VMLINUX_SYMBOL_STR(drm_object_attach_property) },
	{ 0x7ba00036, __VMLINUX_SYMBOL_STR(drm_gem_handle_create) },
	{ 0xb9225f86, __VMLINUX_SYMBOL_STR(drm_gem_dumb_destroy) },
	{ 0xbb91c5ee, __VMLINUX_SYMBOL_STR(vmap) },
	{ 0x2e066dc4, __VMLINUX_SYMBOL_STR(dma_buf_put) },
	{ 0x3882129d, __VMLINUX_SYMBOL_STR(drm_fb_helper_fill_var) },
	{ 0xfacd2e14, __VMLINUX_SYMBOL_STR(pgprot_user) },
	{ 0x7808d2bf, __VMLINUX_SYMBOL_STR(usb_control_msg) },
	{ 0x665f50fa, __VMLINUX_SYMBOL_STR(drm_send_vblank_event) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0xaf835ade, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0xe72407, __VMLINUX_SYMBOL_STR(drm_gem_object_release) },
	{ 0x7d2b8ffb, __VMLINUX_SYMBOL_STR(drm_read) },
	{ 0x15934e80, __VMLINUX_SYMBOL_STR(noop_llseek) },
	{ 0xee684192, __VMLINUX_SYMBOL_STR(drm_add_edid_modes) },
	{ 0x5aa90df1, __VMLINUX_SYMBOL_STR(drm_fb_helper_release_fbi) },
	{ 0x5652ad55, __VMLINUX_SYMBOL_STR(dma_buf_unmap_attachment) },
	{ 0xf6f3ee79, __VMLINUX_SYMBOL_STR(usb_free_coherent) },
	{ 0x1dd71f7a, __VMLINUX_SYMBOL_STR(drm_err) },
	{ 0xee156fa8, __VMLINUX_SYMBOL_STR(drm_connector_init) },
	{ 0x2196324, __VMLINUX_SYMBOL_STR(__aeabi_idiv) },
	{ 0xe927173c, __VMLINUX_SYMBOL_STR(drm_fb_helper_prepare) },
	{ 0x7df4ef4c, __VMLINUX_SYMBOL_STR(drm_gem_vm_open) },
	{ 0x891d305f, __VMLINUX_SYMBOL_STR(drm_mode_connector_update_edid_property) },
	{ 0x3a29fcf7, __VMLINUX_SYMBOL_STR(vm_insert_page) },
	{ 0xc0d84835, __VMLINUX_SYMBOL_STR(drm_gem_vm_close) },
	{ 0x20645642, __VMLINUX_SYMBOL_STR(drm_debug) },
	{ 0x4ea1f5a2, __VMLINUX_SYMBOL_STR(drm_gem_object_free) },
	{ 0xcdd158d, __VMLINUX_SYMBOL_STR(sg_alloc_table) },
	{ 0xbb97d2b7, __VMLINUX_SYMBOL_STR(drm_gem_prime_fd_to_handle) },
	{ 0x29fbe979, __VMLINUX_SYMBOL_STR(dma_buf_begin_cpu_access) },
	{ 0xbda9e3a1, __VMLINUX_SYMBOL_STR(drm_ioctl) },
	{ 0xa6984754, __VMLINUX_SYMBOL_STR(drm_fb_helper_sys_imageblit) },
	{ 0x9bed5a53, __VMLINUX_SYMBOL_STR(usb_submit_urb) },
	{ 0x328d626d, __VMLINUX_SYMBOL_STR(drm_gem_mmap) },
	{ 0x380fae2c, __VMLINUX_SYMBOL_STR(dma_buf_map_attachment) },
	{ 0x8f4fad72, __VMLINUX_SYMBOL_STR(dma_buf_export) },
	{ 0x1195aea8, __VMLINUX_SYMBOL_STR(drm_framebuffer_unregister_private) },
	{ 0xc907fa9a, __VMLINUX_SYMBOL_STR(put_device) },
	{ 0xdb7305a1, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0x4ff7839e, __VMLINUX_SYMBOL_STR(drm_fb_helper_check_var) },
	{ 0x1663f883, __VMLINUX_SYMBOL_STR(drm_fb_helper_blank) },
	{ 0xf455e2f7, __VMLINUX_SYMBOL_STR(drm_gem_object_lookup) },
	{ 0x6ba3cb43, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0xb722c33a, __VMLINUX_SYMBOL_STR(drm_fb_helper_alloc_fbi) },
	{ 0x3f4154be, __VMLINUX_SYMBOL_STR(drm_crtc_init) },
	{ 0x598542b2, __VMLINUX_SYMBOL_STR(_raw_spin_lock_irqsave) },
	{ 0x9d87d14a, __VMLINUX_SYMBOL_STR(dma_buf_attach) },
	{ 0x82cc5e0b, __VMLINUX_SYMBOL_STR(drm_gem_prime_handle_to_fd) },
	{ 0xd2508b7d, __VMLINUX_SYMBOL_STR(get_device) },
	{ 0x247146a6, __VMLINUX_SYMBOL_STR(drm_connector_unregister) },
	{ 0x340607b7, __VMLINUX_SYMBOL_STR(drm_gem_object_init) },
	{ 0xfafd9e4, __VMLINUX_SYMBOL_STR(drm_encoder_cleanup) },
	{ 0xc00777bd, __VMLINUX_SYMBOL_STR(fb_deferred_io_cleanup) },
	{ 0x45496a7d, __VMLINUX_SYMBOL_STR(fb_deferred_io_init) },
	{ 0xe2f00e3c, __VMLINUX_SYMBOL_STR(drm_gem_create_mmap_offset) },
	{ 0x930c8fdf, __VMLINUX_SYMBOL_STR(drm_mode_create_dirty_info_property) },
	{ 0x66e247f5, __VMLINUX_SYMBOL_STR(drm_crtc_cleanup) },
	{ 0x28d6861d, __VMLINUX_SYMBOL_STR(__vmalloc) },
	{ 0xbfb08ca, __VMLINUX_SYMBOL_STR(drm_mode_config_init) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x94961283, __VMLINUX_SYMBOL_STR(vunmap) },
	{ 0xa7ca6829, __VMLINUX_SYMBOL_STR(remap_pfn_range) },
	{ 0x9d669763, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0x4be7fb63, __VMLINUX_SYMBOL_STR(up) },
	{ 0x30d3518a, __VMLINUX_SYMBOL_STR(usb_register_driver) },
	{ 0x1db7dc40, __VMLINUX_SYMBOL_STR(pgprot_kernel) },
	{ 0xcce04bc2, __VMLINUX_SYMBOL_STR(drm_fb_helper_fini) },
	{ 0xe95e0586, __VMLINUX_SYMBOL_STR(drm_modeset_lock_all) },
	{ 0x9cd60539, __VMLINUX_SYMBOL_STR(sg_free_table) },
	{ 0x3e884f4b, __VMLINUX_SYMBOL_STR(vm_get_page_prot) },
	{ 0x49a8bc37, __VMLINUX_SYMBOL_STR(drm_prime_sg_to_page_addr_arrays) },
	{ 0x8f678b07, __VMLINUX_SYMBOL_STR(__stack_chk_guard) },
	{ 0xab0edab6, __VMLINUX_SYMBOL_STR(drm_fb_helper_sys_fillrect) },
	{ 0x44e7d552, __VMLINUX_SYMBOL_STR(drm_modeset_unlock_all) },
	{ 0xa941e698, __VMLINUX_SYMBOL_STR(drm_helper_disable_unused_functions) },
	{ 0x6d3dd188, __VMLINUX_SYMBOL_STR(dma_buf_end_cpu_access) },
	{ 0xad66fd15, __VMLINUX_SYMBOL_STR(drm_fb_helper_setcmap) },
	{ 0xfa3b251c, __VMLINUX_SYMBOL_STR(usb_alloc_coherent) },
	{ 0xad24395f, __VMLINUX_SYMBOL_STR(drm_framebuffer_init) },
	{ 0xc360e7e2, __VMLINUX_SYMBOL_STR(drm_ut_debug_printk) },
	{ 0x9f48322b, __VMLINUX_SYMBOL_STR(dma_buf_vmap) },
	{ 0xb997ed85, __VMLINUX_SYMBOL_STR(drm_fb_helper_sys_copyarea) },
	{ 0x492b0cd9, __VMLINUX_SYMBOL_STR(drm_gem_get_pages) },
	{ 0x67209414, __VMLINUX_SYMBOL_STR(drm_fb_helper_fill_fix) },
	{ 0x602653e1, __VMLINUX_SYMBOL_STR(drm_connector_register) },
	{ 0x3ac1fef9, __VMLINUX_SYMBOL_STR(drm_mode_legacy_fb_format) },
	{ 0xfdab7987, __VMLINUX_SYMBOL_STR(usb_free_urb) },
	{ 0x837d0f0a, __VMLINUX_SYMBOL_STR(down_timeout) },
	{ 0xfa130619, __VMLINUX_SYMBOL_STR(drm_kms_helper_poll_disable) },
	{ 0xfdbebe9e, __VMLINUX_SYMBOL_STR(drm_mode_object_find) },
	{ 0xedcab38, __VMLINUX_SYMBOL_STR(drm_fb_helper_debug_enter) },
	{ 0x9689b1c3, __VMLINUX_SYMBOL_STR(drm_poll) },
	{ 0xb675052f, __VMLINUX_SYMBOL_STR(drm_fb_helper_init) },
	{ 0xc2a27a9b, __VMLINUX_SYMBOL_STR(drm_fb_helper_single_add_all_connectors) },
	{ 0x93d26cd2, __VMLINUX_SYMBOL_STR(usb_alloc_urb) },
	{ 0x41e6c602, __VMLINUX_SYMBOL_STR(drm_open) },
	{ 0x6c21fc42, __VMLINUX_SYMBOL_STR(drm_framebuffer_cleanup) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=";

MODULE_ALIAS("usb:v17E9p*d*dc*dsc*dp*icFFisc00ip00in*");
