#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0xbba89470, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x6c21551d, __VMLINUX_SYMBOL_STR(vfs_create) },
	{ 0x17ef34d1, __VMLINUX_SYMBOL_STR(set_create_files_as) },
	{ 0xbb53c6ea, __VMLINUX_SYMBOL_STR(kmem_cache_destroy) },
	{ 0x6ebd14ab, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0x65e75cb6, __VMLINUX_SYMBOL_STR(__list_del_entry) },
	{ 0x12da5bb2, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0x405c1144, __VMLINUX_SYMBOL_STR(get_seconds) },
	{ 0x882146d4, __VMLINUX_SYMBOL_STR(set_security_override_from_ctx) },
	{ 0x80e1c527, __VMLINUX_SYMBOL_STR(security_path_rename) },
	{ 0xceb886dd, __VMLINUX_SYMBOL_STR(security_inode_mkdir) },
	{ 0x6a112424, __VMLINUX_SYMBOL_STR(up_read) },
	{ 0x349cba85, __VMLINUX_SYMBOL_STR(strchr) },
	{ 0x2e5810c6, __VMLINUX_SYMBOL_STR(__aeabi_unwind_cpp_pr1) },
	{ 0xa0fbac79, __VMLINUX_SYMBOL_STR(wake_up_bit) },
	{ 0x97255bdf, __VMLINUX_SYMBOL_STR(strlen) },
	{ 0xf99c5005, __VMLINUX_SYMBOL_STR(fscache_object_mark_killed) },
	{ 0x6ff10916, __VMLINUX_SYMBOL_STR(prepare_kernel_cred) },
	{ 0xe33c7475, __VMLINUX_SYMBOL_STR(dget_parent) },
	{ 0xc8b57c27, __VMLINUX_SYMBOL_STR(autoremove_wake_function) },
	{ 0x396b9d2c, __VMLINUX_SYMBOL_STR(pagecache_get_page) },
	{ 0xb5198b77, __VMLINUX_SYMBOL_STR(_raw_read_lock) },
	{ 0x20000329, __VMLINUX_SYMBOL_STR(simple_strtoul) },
	{ 0xc4746e8c, __VMLINUX_SYMBOL_STR(touch_atime) },
	{ 0xcdc49e19, __VMLINUX_SYMBOL_STR(lockref_get) },
	{ 0xe8ebaac1, __VMLINUX_SYMBOL_STR(dput) },
	{ 0x2a3aa678, __VMLINUX_SYMBOL_STR(_test_and_clear_bit) },
	{ 0xce079954, __VMLINUX_SYMBOL_STR(dentry_open) },
	{ 0xb1ad28e0, __VMLINUX_SYMBOL_STR(__gnu_mcount_nc) },
	{ 0x28cc25db, __VMLINUX_SYMBOL_STR(arm_copy_from_user) },
	{ 0xe7d8c051, __VMLINUX_SYMBOL_STR(add_to_page_cache_lru) },
	{ 0x81daad6, __VMLINUX_SYMBOL_STR(fscache_object_init) },
	{ 0xf5d58d2, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0xcb2bac98, __VMLINUX_SYMBOL_STR(fscache_object_lookup_negative) },
	{ 0xd41ef057, __VMLINUX_SYMBOL_STR(path_get) },
	{ 0x91715312, __VMLINUX_SYMBOL_STR(sprintf) },
	{ 0xce1233ab, __VMLINUX_SYMBOL_STR(fscache_add_cache) },
	{ 0xfa4a53bb, __VMLINUX_SYMBOL_STR(fscache_check_aux) },
	{ 0x75804391, __VMLINUX_SYMBOL_STR(override_creds) },
	{ 0x442a091f, __VMLINUX_SYMBOL_STR(__alloc_pages_nodemask) },
	{ 0x89ee50b1, __VMLINUX_SYMBOL_STR(security_inode_create) },
	{ 0xc499ae1e, __VMLINUX_SYMBOL_STR(kstrdup) },
	{ 0x7d11c268, __VMLINUX_SYMBOL_STR(jiffies) },
	{ 0x343a1a8, __VMLINUX_SYMBOL_STR(__list_add) },
	{ 0xe6460db0, __VMLINUX_SYMBOL_STR(security_path_unlink) },
	{ 0xf4fa543b, __VMLINUX_SYMBOL_STR(arm_copy_to_user) },
	{ 0xe2d5255a, __VMLINUX_SYMBOL_STR(strcmp) },
	{ 0xf2415352, __VMLINUX_SYMBOL_STR(down_read) },
	{ 0x7bc3445f, __VMLINUX_SYMBOL_STR(unlock_rename) },
	{ 0x25631afd, __VMLINUX_SYMBOL_STR(fscache_cache_cleared_wq) },
	{ 0x275ef902, __VMLINUX_SYMBOL_STR(__init_waitqueue_head) },
	{ 0xb1b4b3c6, __VMLINUX_SYMBOL_STR(kmap_atomic) },
	{ 0x31ad8e5, __VMLINUX_SYMBOL_STR(misc_register) },
	{ 0xfa2a45e, __VMLINUX_SYMBOL_STR(__memzero) },
	{ 0xa816c470, __VMLINUX_SYMBOL_STR(kern_path) },
	{ 0x3de11b98, __VMLINUX_SYMBOL_STR(security_path_mkdir) },
	{ 0x11089ac7, __VMLINUX_SYMBOL_STR(_ctype) },
	{ 0x7ac5b069, __VMLINUX_SYMBOL_STR(__mutex_init) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0xa6a69461, __VMLINUX_SYMBOL_STR(fscache_obtained_object) },
	{ 0x91f5e473, __VMLINUX_SYMBOL_STR(kunmap) },
	{ 0xf6100bd1, __VMLINUX_SYMBOL_STR(vfs_getxattr) },
	{ 0xa1c76e0a, __VMLINUX_SYMBOL_STR(_cond_resched) },
	{ 0x4d9b652b, __VMLINUX_SYMBOL_STR(rb_erase) },
	{ 0x7621ab43, __VMLINUX_SYMBOL_STR(kmem_cache_free) },
	{ 0xfb97f0e9, __VMLINUX_SYMBOL_STR(lock_rename) },
	{ 0xaf835ade, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0xd100acbd, __VMLINUX_SYMBOL_STR(_raw_write_lock) },
	{ 0xed93f29e, __VMLINUX_SYMBOL_STR(__kunmap_atomic) },
	{ 0x521445b, __VMLINUX_SYMBOL_STR(list_del) },
	{ 0x15934e80, __VMLINUX_SYMBOL_STR(noop_llseek) },
	{ 0x10187617, __VMLINUX_SYMBOL_STR(fscache_withdraw_cache) },
	{ 0xdd27fa87, __VMLINUX_SYMBOL_STR(memchr) },
	{ 0xb5b1edbf, __VMLINUX_SYMBOL_STR(unlock_page) },
	{ 0x2e064e03, __VMLINUX_SYMBOL_STR(fput) },
	{ 0xccb2439f, __VMLINUX_SYMBOL_STR(__get_page_tail) },
	{ 0x7f64bdcd, __VMLINUX_SYMBOL_STR(fscache_mark_pages_cached) },
	{ 0xead7a2ec, __VMLINUX_SYMBOL_STR(fscache_mark_page_cached) },
	{ 0x8458f70b, __VMLINUX_SYMBOL_STR(contig_page_data) },
	{ 0x7b08aa7, __VMLINUX_SYMBOL_STR(prepare_creds) },
	{ 0xa1f0ebea, __VMLINUX_SYMBOL_STR(bit_waitqueue) },
	{ 0x632780, __VMLINUX_SYMBOL_STR(work_busy) },
	{ 0x113c9706, __VMLINUX_SYMBOL_STR(mntput) },
	{ 0x783b3563, __VMLINUX_SYMBOL_STR(wake_up_atomic_t) },
	{ 0xc6cbbc89, __VMLINUX_SYMBOL_STR(capable) },
	{ 0x3621cbb8, __VMLINUX_SYMBOL_STR(kmem_cache_alloc) },
	{ 0x4d0d163d, __VMLINUX_SYMBOL_STR(copy_page) },
	{ 0x2efd09c6, __VMLINUX_SYMBOL_STR(kmap) },
	{ 0xf5c0a940, __VMLINUX_SYMBOL_STR(fscache_init_cache) },
	{ 0xdb7305a1, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0x98177fb5, __VMLINUX_SYMBOL_STR(fscache_object_destroy) },
	{ 0x3507a132, __VMLINUX_SYMBOL_STR(_raw_spin_lock_irq) },
	{ 0x17ab16de, __VMLINUX_SYMBOL_STR(vfs_statfs) },
	{ 0xff4e4011, __VMLINUX_SYMBOL_STR(vfs_mkdir) },
	{ 0x3b464854, __VMLINUX_SYMBOL_STR(__put_cred) },
	{ 0x2330651b, __VMLINUX_SYMBOL_STR(path_put) },
	{ 0xeb3189fa, __VMLINUX_SYMBOL_STR(vfs_truncate) },
	{ 0x6ba3cb43, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0x9c0bd51f, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0xd3809d, __VMLINUX_SYMBOL_STR(security_path_mknod) },
	{ 0x66992c82, __VMLINUX_SYMBOL_STR(fscache_put_operation) },
	{ 0xa5526619, __VMLINUX_SYMBOL_STR(rb_insert_color) },
	{ 0x98498fdf, __VMLINUX_SYMBOL_STR(vfs_unlink) },
	{ 0x2a5a9212, __VMLINUX_SYMBOL_STR(kmem_cache_create) },
	{ 0xd85cd67e, __VMLINUX_SYMBOL_STR(__wake_up) },
	{ 0xeb5008da, __VMLINUX_SYMBOL_STR(add_page_wait_queue) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x499cb58c, __VMLINUX_SYMBOL_STR(prepare_to_wait) },
	{ 0x721b1851, __VMLINUX_SYMBOL_STR(skip_spaces) },
	{ 0x6e06bec9, __VMLINUX_SYMBOL_STR(sync_filesystem) },
	{ 0x20f4f7e8, __VMLINUX_SYMBOL_STR(fscache_io_error) },
	{ 0x418f5e6d, __VMLINUX_SYMBOL_STR(abort_creds) },
	{ 0x26e2714c, __VMLINUX_SYMBOL_STR(put_page) },
	{ 0x7b68be1e, __VMLINUX_SYMBOL_STR(__kernel_write) },
	{ 0x1cfb04fa, __VMLINUX_SYMBOL_STR(finish_wait) },
	{ 0x8f678b07, __VMLINUX_SYMBOL_STR(__stack_chk_guard) },
	{ 0x92cf98e, __VMLINUX_SYMBOL_STR(fscache_object_sleep_till_congested) },
	{ 0x676bbc0f, __VMLINUX_SYMBOL_STR(_set_bit) },
	{ 0xb81960ca, __VMLINUX_SYMBOL_STR(snprintf) },
	{ 0xca54fee, __VMLINUX_SYMBOL_STR(_test_and_set_bit) },
	{ 0xc3d6d8f3, __VMLINUX_SYMBOL_STR(fscache_enqueue_operation) },
	{ 0x88b18415, __VMLINUX_SYMBOL_STR(lookup_one_len) },
	{ 0x4ad453b4, __VMLINUX_SYMBOL_STR(vfs_rename) },
	{ 0x49ebacbd, __VMLINUX_SYMBOL_STR(_clear_bit) },
	{ 0x18ae2829, __VMLINUX_SYMBOL_STR(fscache_object_retrying_stale) },
	{ 0xf40595fb, __VMLINUX_SYMBOL_STR(fscache_op_complete) },
	{ 0x72aedf9c, __VMLINUX_SYMBOL_STR(param_ops_uint) },
	{ 0xb236b43f, __VMLINUX_SYMBOL_STR(notify_change) },
	{ 0x2aa0a1a1, __VMLINUX_SYMBOL_STR(vfs_setxattr) },
	{ 0xb5fe184b, __VMLINUX_SYMBOL_STR(misc_deregister) },
	{ 0xab95d144, __VMLINUX_SYMBOL_STR(revert_creds) },
	{ 0xf77b1b88, __VMLINUX_SYMBOL_STR(vfs_removexattr) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=fscache";

