#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0xbba89470, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0xed70f02a, __VMLINUX_SYMBOL_STR(drm_gem_prime_export) },
	{ 0x3627ac9c, __VMLINUX_SYMBOL_STR(component_match_add) },
	{ 0x3349efff, __VMLINUX_SYMBOL_STR(drm_release) },
	{ 0x5d53b6a8, __VMLINUX_SYMBOL_STR(of_find_backlight_by_node) },
	{ 0x6ebd14ab, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0xf1ece412, __VMLINUX_SYMBOL_STR(__pm_runtime_idle) },
	{ 0x8ef918e9, __VMLINUX_SYMBOL_STR(drm_crtc_helper_set_config) },
	{ 0xdd140d82, __VMLINUX_SYMBOL_STR(of_find_i2c_adapter_by_node) },
	{ 0xee951aa3, __VMLINUX_SYMBOL_STR(drm_get_edid) },
	{ 0x8e56a21f, __VMLINUX_SYMBOL_STR(__pm_runtime_disable) },
	{ 0x3a6e410d, __VMLINUX_SYMBOL_STR(drm_framebuffer_reference) },
	{ 0x10e8a17a, __VMLINUX_SYMBOL_STR(component_unbind_all) },
	{ 0x2e5810c6, __VMLINUX_SYMBOL_STR(__aeabi_unwind_cpp_pr1) },
	{ 0x43a53735, __VMLINUX_SYMBOL_STR(__alloc_workqueue_key) },
	{ 0xe5c4bb71, __VMLINUX_SYMBOL_STR(drm_mode_config_cleanup) },
	{ 0x22c1d7a0, __VMLINUX_SYMBOL_STR(drm_flip_work_cleanup) },
	{ 0x26bbcc39, __VMLINUX_SYMBOL_STR(of_parse_phandle) },
	{ 0xe02a2e32, __VMLINUX_SYMBOL_STR(drm_gem_cma_prime_mmap) },
	{ 0x1f35f06e, __VMLINUX_SYMBOL_STR(drm_platform_set_busid) },
	{ 0x5c23444b, __VMLINUX_SYMBOL_STR(pinctrl_select_state) },
	{ 0x47229b5c, __VMLINUX_SYMBOL_STR(gpio_request) },
	{ 0xdfe01d51, __VMLINUX_SYMBOL_STR(no_llseek) },
	{ 0x2ff1905f, __VMLINUX_SYMBOL_STR(devm_pinctrl_get) },
	{ 0x9af2fd11, __VMLINUX_SYMBOL_STR(gpio_to_desc) },
	{ 0x999d2771, __VMLINUX_SYMBOL_STR(drm_helper_probe_single_connector_modes) },
	{ 0xaaa13a94, __VMLINUX_SYMBOL_STR(seq_printf) },
	{ 0xe8e9b5fd, __VMLINUX_SYMBOL_STR(drm_crtc_vblank_off) },
	{ 0xc87c1f84, __VMLINUX_SYMBOL_STR(ktime_get) },
	{ 0x65d9e877, __VMLINUX_SYMBOL_STR(cpufreq_register_notifier) },
	{ 0x768325b5, __VMLINUX_SYMBOL_STR(of_property_read_u32_array) },
	{ 0x8c47d7ae, __VMLINUX_SYMBOL_STR(component_bind_all) },
	{ 0x2e1ca751, __VMLINUX_SYMBOL_STR(clk_put) },
	{ 0x43f7b208, __VMLINUX_SYMBOL_STR(drm_fbdev_cma_init) },
	{ 0xee846c58, __VMLINUX_SYMBOL_STR(drm_vblank_cleanup) },
	{ 0xb1ad28e0, __VMLINUX_SYMBOL_STR(__gnu_mcount_nc) },
	{ 0xf5d58d2, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0x6b53828c, __VMLINUX_SYMBOL_STR(drm_vblank_no_hw_counter) },
	{ 0x15e1de7b, __VMLINUX_SYMBOL_STR(__pm_runtime_resume) },
	{ 0xd33425b2, __VMLINUX_SYMBOL_STR(i2c_put_adapter) },
	{ 0x28b4030e, __VMLINUX_SYMBOL_STR(drm_vblank_init) },
	{ 0xef4b1e4b, __VMLINUX_SYMBOL_STR(component_master_del) },
	{ 0xc0f66d34, __VMLINUX_SYMBOL_STR(drm_encoder_init) },
	{ 0x24989fa2, __VMLINUX_SYMBOL_STR(drm_gem_cma_prime_get_sg_table) },
	{ 0x556e4390, __VMLINUX_SYMBOL_STR(clk_get_rate) },
	{ 0x2519e068, __VMLINUX_SYMBOL_STR(pinctrl_lookup_state) },
	{ 0x129f3122, __VMLINUX_SYMBOL_STR(__platform_driver_register) },
	{ 0x343a1a8, __VMLINUX_SYMBOL_STR(__list_add) },
	{ 0x3a4f03be, __VMLINUX_SYMBOL_STR(drm_gem_cma_vm_ops) },
	{ 0xae8eae1f, __VMLINUX_SYMBOL_STR(drm_connector_cleanup) },
	{ 0x6214aef2, __VMLINUX_SYMBOL_STR(cpufreq_unregister_notifier) },
	{ 0x275ef902, __VMLINUX_SYMBOL_STR(__init_waitqueue_head) },
	{ 0xd2335101, __VMLINUX_SYMBOL_STR(drm_fb_get_bpp_depth) },
	{ 0x54541cfc, __VMLINUX_SYMBOL_STR(drm_flip_work_queue) },
	{ 0x9aacf272, __VMLINUX_SYMBOL_STR(drm_handle_vblank) },
	{ 0xb637065d, __VMLINUX_SYMBOL_STR(drm_helper_connector_dpms) },
	{ 0xa776c9f6, __VMLINUX_SYMBOL_STR(drm_mode_connector_attach_encoder) },
	{ 0x415a3f, __VMLINUX_SYMBOL_STR(drm_irq_install) },
	{ 0x134ddc3f, __VMLINUX_SYMBOL_STR(drm_fb_cma_debugfs_show) },
	{ 0xcc337fd5, __VMLINUX_SYMBOL_STR(drm_fbdev_cma_restore_mode) },
	{ 0x5adeb95d, __VMLINUX_SYMBOL_STR(dev_err) },
	{ 0x51d559d1, __VMLINUX_SYMBOL_STR(_raw_spin_unlock_irqrestore) },
	{ 0x6a4dcc5c, __VMLINUX_SYMBOL_STR(drm_mode_set_name) },
	{ 0x9f4cd1df, __VMLINUX_SYMBOL_STR(of_device_is_available) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0xdb48b436, __VMLINUX_SYMBOL_STR(drm_gem_cma_dumb_create) },
	{ 0x28446033, __VMLINUX_SYMBOL_STR(drm_put_dev) },
	{ 0xa789dd0c, __VMLINUX_SYMBOL_STR(of_graph_get_next_endpoint) },
	{ 0x79c5a9f0, __VMLINUX_SYMBOL_STR(ioremap) },
	{ 0xb1bbca04, __VMLINUX_SYMBOL_STR(of_find_property) },
	{ 0xb9225f86, __VMLINUX_SYMBOL_STR(drm_gem_dumb_destroy) },
	{ 0x1a8cf2d2, __VMLINUX_SYMBOL_STR(drm_crtc_vblank_on) },
	{ 0x66add0f0, __VMLINUX_SYMBOL_STR(drm_fb_cma_get_gem_obj) },
	{ 0xa1c76e0a, __VMLINUX_SYMBOL_STR(_cond_resched) },
	{ 0xb2c912af, __VMLINUX_SYMBOL_STR(drm_fbdev_cma_hotplug_event) },
	{ 0x665f50fa, __VMLINUX_SYMBOL_STR(drm_send_vblank_event) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0x3d06c661, __VMLINUX_SYMBOL_STR(drm_gem_cma_mmap) },
	{ 0xaf835ade, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0x8b85baef, __VMLINUX_SYMBOL_STR(drm_probe_ddc) },
	{ 0x8c03d20c, __VMLINUX_SYMBOL_STR(destroy_workqueue) },
	{ 0x65f3639b, __VMLINUX_SYMBOL_STR(drm_fb_cma_create) },
	{ 0x521445b, __VMLINUX_SYMBOL_STR(list_del) },
	{ 0xc13ce2de, __VMLINUX_SYMBOL_STR(drm_framebuffer_unreference) },
	{ 0x4a31d399, __VMLINUX_SYMBOL_STR(platform_get_resource) },
	{ 0x7d2b8ffb, __VMLINUX_SYMBOL_STR(drm_read) },
	{ 0xee684192, __VMLINUX_SYMBOL_STR(drm_add_edid_modes) },
	{ 0xab36926f, __VMLINUX_SYMBOL_STR(drm_display_mode_from_videomode) },
	{ 0x2f199c7, __VMLINUX_SYMBOL_STR(gpiod_direction_output_raw) },
	{ 0xb9448af4, __VMLINUX_SYMBOL_STR(pinctrl_pm_select_sleep_state) },
	{ 0xd85f6fba, __VMLINUX_SYMBOL_STR(drm_debugfs_create_files) },
	{ 0xf6b13494, __VMLINUX_SYMBOL_STR(drm_platform_init) },
	{ 0xee156fa8, __VMLINUX_SYMBOL_STR(drm_connector_init) },
	{ 0x24085454, __VMLINUX_SYMBOL_STR(drm_kms_helper_poll_enable) },
	{ 0x42160169, __VMLINUX_SYMBOL_STR(flush_workqueue) },
	{ 0x2196324, __VMLINUX_SYMBOL_STR(__aeabi_idiv) },
	{ 0xb8b425b3, __VMLINUX_SYMBOL_STR(of_find_node_by_phandle) },
	{ 0x891d305f, __VMLINUX_SYMBOL_STR(drm_mode_connector_update_edid_property) },
	{ 0x210dc07c, __VMLINUX_SYMBOL_STR(of_get_child_by_name) },
	{ 0x20645642, __VMLINUX_SYMBOL_STR(drm_debug) },
	{ 0x96ef29c0, __VMLINUX_SYMBOL_STR(of_get_display_timings) },
	{ 0xbb97d2b7, __VMLINUX_SYMBOL_STR(drm_gem_prime_fd_to_handle) },
	{ 0xbda9e3a1, __VMLINUX_SYMBOL_STR(drm_ioctl) },
	{ 0x234061b4, __VMLINUX_SYMBOL_STR(drm_gem_prime_import) },
	{ 0xf8625e4e, __VMLINUX_SYMBOL_STR(_dev_info) },
	{ 0x2e21906a, __VMLINUX_SYMBOL_STR(drm_mode_create) },
	{ 0x12a38747, __VMLINUX_SYMBOL_STR(usleep_range) },
	{ 0x8e2b25c2, __VMLINUX_SYMBOL_STR(videomode_from_timings) },
	{ 0xacaff8e6, __VMLINUX_SYMBOL_STR(pm_runtime_enable) },
	{ 0xc907fa9a, __VMLINUX_SYMBOL_STR(put_device) },
	{ 0xdb7305a1, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0xe2b13922, __VMLINUX_SYMBOL_STR(drm_gem_cma_prime_vunmap) },
	{ 0xd62c833f, __VMLINUX_SYMBOL_STR(schedule_timeout) },
	{ 0x72350130, __VMLINUX_SYMBOL_STR(___ratelimit) },
	{ 0x450318e2, __VMLINUX_SYMBOL_STR(drm_irq_uninstall) },
	{ 0x2be40654, __VMLINUX_SYMBOL_STR(of_get_named_gpio_flags) },
	{ 0xb90fad6f, __VMLINUX_SYMBOL_STR(pinctrl_pm_select_default_state) },
	{ 0x7b9fbf85, __VMLINUX_SYMBOL_STR(drm_flip_work_commit) },
	{ 0x6ba3cb43, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0x3f4154be, __VMLINUX_SYMBOL_STR(drm_crtc_init) },
	{ 0x485ec4d6, __VMLINUX_SYMBOL_STR(__dynamic_dev_dbg) },
	{ 0x598542b2, __VMLINUX_SYMBOL_STR(_raw_spin_lock_irqsave) },
	{ 0x82cc5e0b, __VMLINUX_SYMBOL_STR(drm_gem_prime_handle_to_fd) },
	{ 0x289257a3, __VMLINUX_SYMBOL_STR(clk_get) },
	{ 0x76d9b876, __VMLINUX_SYMBOL_STR(clk_set_rate) },
	{ 0xe0f27cc1, __VMLINUX_SYMBOL_STR(drm_gem_cma_prime_import_sg_table) },
	{ 0xd85cd67e, __VMLINUX_SYMBOL_STR(__wake_up) },
	{ 0x247146a6, __VMLINUX_SYMBOL_STR(drm_connector_unregister) },
	{ 0xfafd9e4, __VMLINUX_SYMBOL_STR(drm_encoder_cleanup) },
	{ 0xa8b4c151, __VMLINUX_SYMBOL_STR(devm_gpiod_get_optional) },
	{ 0x344b7739, __VMLINUX_SYMBOL_STR(prepare_to_wait_event) },
	{ 0xfe990052, __VMLINUX_SYMBOL_STR(gpio_free) },
	{ 0x822137e2, __VMLINUX_SYMBOL_STR(arm_heavy_mb) },
	{ 0x3254c792, __VMLINUX_SYMBOL_STR(of_graph_get_remote_port_parent) },
	{ 0x66e247f5, __VMLINUX_SYMBOL_STR(drm_crtc_cleanup) },
	{ 0xbfb08ca, __VMLINUX_SYMBOL_STR(drm_mode_config_init) },
	{ 0x30e15c12, __VMLINUX_SYMBOL_STR(devm_pinctrl_put) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0xedc03953, __VMLINUX_SYMBOL_STR(iounmap) },
	{ 0xd94aa457, __VMLINUX_SYMBOL_STR(display_timings_release) },
	{ 0xf9375a01, __VMLINUX_SYMBOL_STR(gpiod_set_value_cansleep) },
	{ 0x29785510, __VMLINUX_SYMBOL_STR(drm_debugfs_remove_files) },
	{ 0x1cfb04fa, __VMLINUX_SYMBOL_STR(finish_wait) },
	{ 0xa142614c, __VMLINUX_SYMBOL_STR(drm_flip_work_init) },
	{ 0xb9367be5, __VMLINUX_SYMBOL_STR(dev_warn) },
	{ 0x8f678b07, __VMLINUX_SYMBOL_STR(__stack_chk_guard) },
	{ 0x3150d644, __VMLINUX_SYMBOL_STR(drm_mode_probed_add) },
	{ 0x67d2fa02, __VMLINUX_SYMBOL_STR(component_master_add_with_match) },
	{ 0x1148b623, __VMLINUX_SYMBOL_STR(drm_fbdev_cma_fini) },
	{ 0x90e3dcb5, __VMLINUX_SYMBOL_STR(platform_get_irq) },
	{ 0x2d2dcca0, __VMLINUX_SYMBOL_STR(platform_driver_unregister) },
	{ 0xc360e7e2, __VMLINUX_SYMBOL_STR(drm_ut_debug_printk) },
	{ 0x19c6710c, __VMLINUX_SYMBOL_STR(drm_kms_helper_poll_init) },
	{ 0x721320f4, __VMLINUX_SYMBOL_STR(drm_gem_cma_free_object) },
	{ 0xa2ba3b13, __VMLINUX_SYMBOL_STR(drm_gem_cma_prime_vmap) },
	{ 0xeda13d45, __VMLINUX_SYMBOL_STR(of_node_put) },
	{ 0x8d3060dd, __VMLINUX_SYMBOL_STR(devm_kmalloc) },
	{ 0x602653e1, __VMLINUX_SYMBOL_STR(drm_connector_register) },
	{ 0xfa130619, __VMLINUX_SYMBOL_STR(drm_kms_helper_poll_disable) },
	{ 0x9689b1c3, __VMLINUX_SYMBOL_STR(drm_poll) },
	{ 0x6ec106b0, __VMLINUX_SYMBOL_STR(drm_mm_dump_table) },
	{ 0xe9a290f, __VMLINUX_SYMBOL_STR(drm_gem_cma_dumb_map_offset) },
	{ 0xe9dfb337, __VMLINUX_SYMBOL_STR(drm_mode_vrefresh) },
	{ 0x41e6c602, __VMLINUX_SYMBOL_STR(drm_open) },
	{ 0x90313263, __VMLINUX_SYMBOL_STR(drm_kms_helper_poll_fini) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=";

MODULE_ALIAS("of:N*T*Cti,am33xx-tilcdc*");
