#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0xbba89470, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x68abb700, __VMLINUX_SYMBOL_STR(kobject_put) },
	{ 0x2d3385d3, __VMLINUX_SYMBOL_STR(system_wq) },
	{ 0x6ebd14ab, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0x65e75cb6, __VMLINUX_SYMBOL_STR(__list_del_entry) },
	{ 0xbfea5292, __VMLINUX_SYMBOL_STR(drm_vma_offset_remove) },
	{ 0x12da5bb2, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0x6a112424, __VMLINUX_SYMBOL_STR(up_read) },
	{ 0x8a2d86f5, __VMLINUX_SYMBOL_STR(mem_map) },
	{ 0x2adf2fe1, __VMLINUX_SYMBOL_STR(__ww_mutex_lock_interruptible) },
	{ 0x586d342e, __VMLINUX_SYMBOL_STR(drm_class_device_unregister) },
	{ 0x3abb26b0, __VMLINUX_SYMBOL_STR(ioremap_wc) },
	{ 0x7aa1756e, __VMLINUX_SYMBOL_STR(kvfree) },
	{ 0x2e5810c6, __VMLINUX_SYMBOL_STR(__aeabi_unwind_cpp_pr1) },
	{ 0xd2af138b, __VMLINUX_SYMBOL_STR(reservation_ww_class) },
	{ 0x134bb9b3, __VMLINUX_SYMBOL_STR(page_address) },
	{ 0x43a53735, __VMLINUX_SYMBOL_STR(__alloc_workqueue_key) },
	{ 0x36d74878, __VMLINUX_SYMBOL_STR(reservation_object_wait_timeout_rcu) },
	{ 0x19f462ab, __VMLINUX_SYMBOL_STR(kfree_call_rcu) },
	{ 0x6e7f59e, __VMLINUX_SYMBOL_STR(send_sig) },
	{ 0x39a0686a, __VMLINUX_SYMBOL_STR(arm_dma_ops) },
	{ 0xb5198b77, __VMLINUX_SYMBOL_STR(_raw_read_lock) },
	{ 0xf7802486, __VMLINUX_SYMBOL_STR(__aeabi_uidivmod) },
	{ 0x6b06fdce, __VMLINUX_SYMBOL_STR(delayed_work_timer_fn) },
	{ 0xd1e79cae, __VMLINUX_SYMBOL_STR(fence_wait_timeout) },
	{ 0xaaa13a94, __VMLINUX_SYMBOL_STR(seq_printf) },
	{ 0x44b1d426, __VMLINUX_SYMBOL_STR(__dynamic_pr_debug) },
	{ 0x987c11c7, __VMLINUX_SYMBOL_STR(__pv_phys_pfn_offset) },
	{ 0xe93e49c3, __VMLINUX_SYMBOL_STR(devres_free) },
	{ 0xb1ad28e0, __VMLINUX_SYMBOL_STR(__gnu_mcount_nc) },
	{ 0xd70c8470, __VMLINUX_SYMBOL_STR(drm_mm_debug_table) },
	{ 0x9580deb, __VMLINUX_SYMBOL_STR(init_timer_key) },
	{ 0x29a010e6, __VMLINUX_SYMBOL_STR(drm_mm_insert_node_in_range_generic) },
	{ 0x4c29dcbf, __VMLINUX_SYMBOL_STR(cancel_delayed_work_sync) },
	{ 0xf5d58d2, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0xadd47e82, __VMLINUX_SYMBOL_STR(kobject_del) },
	{ 0x831396c3, __VMLINUX_SYMBOL_STR(fence_signal) },
	{ 0xdbb5a9f5, __VMLINUX_SYMBOL_STR(drm_ht_remove_item) },
	{ 0x22cb3e42, __VMLINUX_SYMBOL_STR(drm_vma_offset_lookup_locked) },
	{ 0x40c7247c, __VMLINUX_SYMBOL_STR(si_meminfo) },
	{ 0x442a091f, __VMLINUX_SYMBOL_STR(__alloc_pages_nodemask) },
	{ 0x98134336, __VMLINUX_SYMBOL_STR(devres_alloc_node) },
	{ 0xc2a4f192, __VMLINUX_SYMBOL_STR(set_page_dirty) },
	{ 0x343a1a8, __VMLINUX_SYMBOL_STR(__list_add) },
	{ 0x66b195f3, __VMLINUX_SYMBOL_STR(mutex_trylock) },
	{ 0x80e3cb7, __VMLINUX_SYMBOL_STR(reservation_object_add_shared_fence) },
	{ 0x275ef902, __VMLINUX_SYMBOL_STR(__init_waitqueue_head) },
	{ 0xb1b4b3c6, __VMLINUX_SYMBOL_STR(kmap_atomic) },
	{ 0xfa2a45e, __VMLINUX_SYMBOL_STR(__memzero) },
	{ 0x1a546ddd, __VMLINUX_SYMBOL_STR(drm_mm_init) },
	{ 0xc084b7f7, __VMLINUX_SYMBOL_STR(drm_vma_offset_manager_destroy) },
	{ 0x51d559d1, __VMLINUX_SYMBOL_STR(_raw_spin_unlock_irqrestore) },
	{ 0x23fd6c4e, __VMLINUX_SYMBOL_STR(mutex_lock_interruptible) },
	{ 0x7ac5b069, __VMLINUX_SYMBOL_STR(__mutex_init) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0x20c55ae0, __VMLINUX_SYMBOL_STR(sscanf) },
	{ 0x79c5a9f0, __VMLINUX_SYMBOL_STR(ioremap) },
	{ 0xa13f2b11, __VMLINUX_SYMBOL_STR(kobject_init_and_add) },
	{ 0xe51d89b5, __VMLINUX_SYMBOL_STR(drm_mm_clean) },
	{ 0xbb91c5ee, __VMLINUX_SYMBOL_STR(vmap) },
	{ 0x91f5e473, __VMLINUX_SYMBOL_STR(kunmap) },
	{ 0xcbf7553a, __VMLINUX_SYMBOL_STR(dma_buf_fd) },
	{ 0x2e066dc4, __VMLINUX_SYMBOL_STR(dma_buf_put) },
	{ 0x9e22097a, __VMLINUX_SYMBOL_STR(fence_enable_sw_signaling) },
	{ 0xa80c979d, __VMLINUX_SYMBOL_STR(shmem_read_mapping_page_gfp) },
	{ 0xa1c76e0a, __VMLINUX_SYMBOL_STR(_cond_resched) },
	{ 0x3eb37b9d, __VMLINUX_SYMBOL_STR(drm_ht_create) },
	{ 0x3957ae9e, __VMLINUX_SYMBOL_STR(dma_buf_get) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0xaf835ade, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0xed93f29e, __VMLINUX_SYMBOL_STR(__kunmap_atomic) },
	{ 0x21110dbf, __VMLINUX_SYMBOL_STR(mmioset) },
	{ 0x8c03d20c, __VMLINUX_SYMBOL_STR(destroy_workqueue) },
	{ 0x521445b, __VMLINUX_SYMBOL_STR(list_del) },
	{ 0x4d8f392e, __VMLINUX_SYMBOL_STR(__ww_mutex_lock) },
	{ 0x611c529b, __VMLINUX_SYMBOL_STR(dma_release_from_coherent) },
	{ 0xe7197773, __VMLINUX_SYMBOL_STR(drm_ht_insert_item) },
	{ 0x2e064e03, __VMLINUX_SYMBOL_STR(fput) },
	{ 0x42160169, __VMLINUX_SYMBOL_STR(flush_workqueue) },
	{ 0x7c45f111, __VMLINUX_SYMBOL_STR(shmem_file_setup) },
	{ 0x8458f70b, __VMLINUX_SYMBOL_STR(contig_page_data) },
	{ 0x6aa70036, __VMLINUX_SYMBOL_STR(dma_alloc_from_coherent) },
	{ 0x2f436d2a, __VMLINUX_SYMBOL_STR(mark_page_accessed) },
	{ 0xc6cbbc89, __VMLINUX_SYMBOL_STR(capable) },
	{ 0xae4b94c, __VMLINUX_SYMBOL_STR(drm_ht_remove) },
	{ 0x568e5a7b, __VMLINUX_SYMBOL_STR(__free_pages) },
	{ 0x2affdfa4, __VMLINUX_SYMBOL_STR(unregister_shrinker) },
	{ 0x4d0d163d, __VMLINUX_SYMBOL_STR(copy_page) },
	{ 0xc2e1a6e8, __VMLINUX_SYMBOL_STR(drm_clflush_pages) },
	{ 0x2efd09c6, __VMLINUX_SYMBOL_STR(kmap) },
	{ 0x8f4fad72, __VMLINUX_SYMBOL_STR(dma_buf_export) },
	{ 0x3f616ce2, __VMLINUX_SYMBOL_STR(queue_delayed_work_on) },
	{ 0xdb7305a1, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0x59aa14cf, __VMLINUX_SYMBOL_STR(fence_release) },
	{ 0x1000e51, __VMLINUX_SYMBOL_STR(schedule) },
	{ 0x8a7d1c31, __VMLINUX_SYMBOL_STR(high_memory) },
	{ 0xaca28f91, __VMLINUX_SYMBOL_STR(drm_class_device_register) },
	{ 0x2991bf5b, __VMLINUX_SYMBOL_STR(dev_driver_string) },
	{ 0x8e258b25, __VMLINUX_SYMBOL_STR(devres_add) },
	{ 0x8eff9111, __VMLINUX_SYMBOL_STR(drm_ht_find_item) },
	{ 0x6ba3cb43, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0x9c0bd51f, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0xfbdadf27, __VMLINUX_SYMBOL_STR(reservation_object_add_excl_fence) },
	{ 0x485ec4d6, __VMLINUX_SYMBOL_STR(__dynamic_dev_dbg) },
	{ 0x598542b2, __VMLINUX_SYMBOL_STR(_raw_spin_lock_irqsave) },
	{ 0xd85cd67e, __VMLINUX_SYMBOL_STR(__wake_up) },
	{ 0xd64afb6f, __VMLINUX_SYMBOL_STR(drm_vma_offset_add) },
	{ 0x344b7739, __VMLINUX_SYMBOL_STR(prepare_to_wait_event) },
	{ 0x9629aab3, __VMLINUX_SYMBOL_STR(vm_insert_mixed) },
	{ 0x822137e2, __VMLINUX_SYMBOL_STR(arm_heavy_mb) },
	{ 0x28d6861d, __VMLINUX_SYMBOL_STR(__vmalloc) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x94961283, __VMLINUX_SYMBOL_STR(vunmap) },
	{ 0xff667492, __VMLINUX_SYMBOL_STR(unmap_mapping_range) },
	{ 0x9d669763, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0xee94602d, __VMLINUX_SYMBOL_STR(register_shrinker) },
	{ 0xedc03953, __VMLINUX_SYMBOL_STR(iounmap) },
	{ 0x39fabd54, __VMLINUX_SYMBOL_STR(ww_mutex_unlock) },
	{ 0x26e2714c, __VMLINUX_SYMBOL_STR(put_page) },
	{ 0xb6efa451, __VMLINUX_SYMBOL_STR(devres_destroy) },
	{ 0x1db7dc40, __VMLINUX_SYMBOL_STR(pgprot_kernel) },
	{ 0xdd150721, __VMLINUX_SYMBOL_STR(drm_mm_takedown) },
	{ 0x1cfb04fa, __VMLINUX_SYMBOL_STR(finish_wait) },
	{ 0x216d759a, __VMLINUX_SYMBOL_STR(mmiocpy) },
	{ 0x3e884f4b, __VMLINUX_SYMBOL_STR(vm_get_page_prot) },
	{ 0x8f678b07, __VMLINUX_SYMBOL_STR(__stack_chk_guard) },
	{ 0xcd0fc417, __VMLINUX_SYMBOL_STR(drm_ht_just_insert_please) },
	{ 0x676bbc0f, __VMLINUX_SYMBOL_STR(_set_bit) },
	{ 0xb2d48a2e, __VMLINUX_SYMBOL_STR(queue_work_on) },
	{ 0xb81960ca, __VMLINUX_SYMBOL_STR(snprintf) },
	{ 0x85cddcd4, __VMLINUX_SYMBOL_STR(vmalloc_to_page) },
	{ 0x28352af3, __VMLINUX_SYMBOL_STR(dev_set_name) },
	{ 0xb23e17f6, __VMLINUX_SYMBOL_STR(reservation_object_reserve_shared) },
	{ 0xa4466414, __VMLINUX_SYMBOL_STR(drm_mm_remove_node) },
	{ 0x3b7a8f6b, __VMLINUX_SYMBOL_STR(drm_vma_offset_manager_init) },
	{ 0x49ebacbd, __VMLINUX_SYMBOL_STR(_clear_bit) },
	{ 0x8163e3ac, __VMLINUX_SYMBOL_STR(vm_insert_pfn) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=";

